### ISSUE TITLE
Hide startup messages with custom image

### ISSUE THREAD

**Issue by thijstriemstra** [FooDeas/raspberrypi-ua-netinst#10]
It would be really nice to be able to specify a custom boot logo and hide the system startup messages.

I would then start my app, which it's already doing using a systemd service, but it shows the login prompt for a couple seconds during the app startup that I'd also like to mask with the boot logo image.

**Comment by bassemolufda** [comment]
Hi thijstriemstra,

i found a Script called asplashscreen with google. Maybe this hels you?

```
#! /bin/sh
### BEGIN INIT INFO
# Provides:          asplashscreen
# Required-Start:
# Required-Stop:
# Should-Start:
# Default-Start:     S
# Default-Stop:
# Short-Description: Show custom splashscreen
# Description:       Show custom splashscreen
### END INIT INFO


do_start () {

    /usr/bin/fbi -T 1 -noverbose -a /etc/splash/splash.png
    exit 0
}

case "$1" in
  start|"")
    do_start
    ;;
  restart|reload|force-reload)
    echo "Error: argument '$1' not supported" >&2
    exit 3
    ;;
  stop)
    # No-op
    ;;
  status)
    exit 0
    ;;
  *)
    echo "Usage: asplashscreen [start|stop]" >&2
    exit 3
    ;;
esac

:
```

sincelery Uwe

**Comment by thijstriemstra** [comment]
thanks for the suggestion @bassemolufda

**Comment by FooDeas** [comment]
Additionally you may have to replace `loglevel=3` with `quiet` in `/boot/cmdline.txt`.

**Comment by thijstriemstra** [comment]
Thanks for that addition @FooDeas. Is it possible to also [hide the pi logo](http://www.instructables.com/id/Raspberry-Pi-Digital-Signage-Exchange-Rate-Display/step17/Hiding-the-Raspberry-Pi-Logo-on-startup/) as described here with a new option? Apparently you'll also see a flash text cursor, this can be disabled with `vt.global_cursor_default=0`.

**Comment by thijstriemstra** [comment]
Looks like video is [also supported](http://blog.sheasilverman.com/2013/09/adding-a-startup-movie-to-your-raspberry-pi/) with the same `asplashscreen` script, very cool.

**Comment by thijstriemstra** [comment]
Note to self: the asplashscreen script also needs a `# Required-Start: $local_fs` according to [this comment](http://blog.sheasilverman.com/2013/09/adding-a-startup-movie-to-your-raspberry-pi/#comment-30252).

**Comment by FooDeas** [comment]
The `asplashscreen` script adding/customization should be done via `install_files` (see `README.md`).
The `logo.nologo` kernel parameter will be added to next version with the `quiet_boot=1` option.

**Comment by thijstriemstra** [comment]
The latest raspbian has this nice 'pixel' startup image. Any way we can add an option that allows you to replace/add such an image?

**Comment by FooDeas** [comment]
Any info which way they implemented that?
