### ISSUE TITLE
Move retries to config

### ISSUE THREAD

**Issue by thijstriemstra** [FooDeas/raspberrypi-ua-netinst#100]
There's a couple of retries that are harcoded, let's move them to a config and enforce a default when they're not supplied in a config.

**Comment by ghost** [comment]
It would be great if all those retries (the currently hardcoded ones but also the 'installer-retries.txt') are merged into the central 'installer-config.txt'.

The 'installer-retries.txt' currently has two purposes:
1.) It is used as configuration file to initially set the number of desired installation retries.
2.) It is used as counter file that the installer uses to save the actual number of retries.

It would be great if the configuration part could be moved to the central 'installer-config.txt' and the counter file is moved away from the configuration directory and for example placed in the same directory where the error-logs are stored if the installation fails.
In my opinion the configuration directory should be reserved for the user to provide his settings and the content of this directory should not be modified by the installer at any time.
