### ISSUE TITLE
Allow installer progress to be monitored from the local network

### ISSUE THREAD

**Issue by dinosore** [FooDeas/raspberrypi-ua-netinst#112]
I haven't worked out the details, but it might be possible to implement a lightweight solution using nmap.

nmap, I believe, was originally BSD, but has ben widely adopted in Linux.  I don't know about mac.

Windows 10 pcs are covered with embedded Ubuntu.

**Comment by mpmc** [comment]
How about http://mqtt.org/ ?

**Comment by FooDeas** [comment]
I have an idea implementing this by serving a simple, one directional, buffered telnet connection output.
Coming very soon!

**Comment by FooDeas** [comment]
Done with 4c9588e30ab6898bd3353aff3a71a203e42a8e7d.

**Comment by dinosore** [comment]
Works well.  I'm very impressed with the implementation of this feature.  Well done!

**Comment by Mausy5043** [comment]
Can't figure out how this would work on my Mac. Any suggestions?

**EDIT**: Oh I see now.  
`telnet` is not installed by default on macOS. Using `brew` I could `brew install telnet`.
That fixed it for me.
