### ISSUE TITLE
Preset package selection

### ISSUE THREAD

**Issue by ghost** [FooDeas/raspberrypi-ua-netinst#113]
During a review of the package list for the 'preset=base' setting I have noted the following:

-) cpufrequtils
This package basically provides an "user-friendly" tool to configure various settings of the CPU by writing the required values to the linux kernel interface (procfs and sysfs).
However these settings can also be performed manually with standard linux tools.
In my opinion, the purpose of the 'preset=base' setting is to include only the bare essential packages, that are required for the installation to complete and to get a bootable system.
Therefore I would propose to move the 'cpufrequtils'-package from the base to the minimum preset.

-) raspbian-archive-keyring
This package is a dependency of the 'apt'-package and therefore always automatically included in the installation.
In my opinion there is no need to explicitly include it in the 'preset=base' package list and I would propose to remove it from the list.

I have opened this issue to find out whether there are any objections on these proposed changes.

**Comment by FooDeas** [comment]
👍
