### ISSUE TITLE
Installer hangs when updating...?

### ISSUE THREAD

**Issue by mike632t** [FooDeas/raspberrypi-ua-netinst#119]
When installing on a Raspberry Pi 2 Model B Rev 1.1 everything seems to start off working as expected but the install seems to hang after about 15-20 minutes while updating the kernel.

There does not seem to be an error log created.

Last output is as follows

Configuring apt:
  Configuring Raspbian repository... OK
  Checking Raspbian repository entry... OK
  Adding raspberrypi.org GPG key to apt-key... OK
  Configuring RaspberryPi repository... OK
  Configuring RaspberryPi preference... OK

Updating package lists... OK

Downloading packages...
  Reading package lists...
  Building dependency tree...
  Reading state information...
  The following additional packages will be installed:
    device-tree-compiler libcap2-bin libpam-cap libraspberrypi0
  The following NEW packages will be installed:
    device-tree-compiler libcap2-bin libpam-cap libraspberrypi-bin
    libraspberrypi0 raspberrypi-bootloader raspberrypi-kernel
    raspberrypi-sys-mods raspi-copies-and-fills
  0 upgraded, 9 newly installed, 0 to remove and 4 not upgraded.
  Need to get 36.8 MB of archives.
  After this operation, 132 MB of additional disk space will be used.
  Get:1 http://archive.raspberrypi.org/debian stretch/main armhf raspberrypi-sys-mods armhf 20171127 [9090 B]
  Get:2 http://archive.raspberrypi.org/debian stretch/main armhf raspi-copies-and-fills armhf 0.6 [7226 B]
  Get:3 http://archive.raspberrypi.org/debian stretch/main armhf device-tree-compiler armhf 1.4.4-1 [349 kB]
  Get:4 http://archive.raspberrypi.org/debian stretch/main armhf raspberrypi-bootloader armhf 1.20171029-1 [3513 kB]
  Get:5 http://archive.raspberrypi.org/debian stretch/main armhf libraspberrypi0 armhf 1.20171029-1 [837 kB]
  Get:6 http://archive.raspberrypi.org/debian stretch/main armhf libraspberrypi-bin armhf 1.20171029-1 [335 kB]
  Get:7 http://archive.raspberrypi.org/debian stretch/main armhf raspberrypi-kernel armhf 1.20171029-1 [31.7 MB]

**Comment by Mausy5043** [comment]
I get that too sometimes. Then after a couple of hours everything works great. Could be high traffic. Try again at a later moment.
I just tried the `raspberrypi-kernel` @ 20171224T21:04  Had no problems

**Comment by mike632t** [comment]
I've tried three different models of PI and a couple of different SD cards but the result is the same every time.

**Comment by FooDeas** [comment]
It must have something to do with your connection.
Can you download the kernel [manually](http://archive.raspberrypi.org/debian/pool/main/r/raspberrypi-firmware/raspberrypi-kernel_1.20171029-1_armhf.deb)?
Are you behind a proxy/firewall?
Which installer version are you using?

**Comment by mike632t** [comment]
I am behind a couple of firewalls but I can download the kernel maunally using my browser and wget (no proxy set).

Using a Pi Zero W with a USB network adapter (wired) with installer version 2.0.0.

No issues getting all the other packages but I wonder if I am running out of memory or disk space ..

**Comment by mike632t** [comment]
Full console output attached (password modified)

[2.0.0_console_log.txt](https://github.com/FooDeas/raspberrypi-ua-netinst/files/1590087/2.0.0_console_log.txt)

**Comment by FooDeas** [comment]
It's no out of memory or space problem.
Try to disable IPv6.

**Comment by mike632t** [comment]
Disabled IPv6 in the installer-config.txt - No change
I can 'see' the traffic on the firewall as the file downloads, and the green LED on the Pi blinks as it is written to the SD card, but then nothing else happens...

**Comment by Mausy5043** [comment]
raspberrypi.org still has issues:

```
$ ping archive.raspberrypi.org
ping: archive.raspberrypi.org: Temporary failure in name resolution
$ ping raspberrypi.org
ping: raspberrypi.org: Temporary failure in name resolution
```

This could be related.
You could try pointing your webbrowser at `http://raspberrypi.org` when this happens to confirm the problem.  
Probably lots of people sitting at home trying to do the same thing, overloading that host.

**Comment by FooDeas** [comment]
Tricky... Does it keep flashing or stops?
Another idea: Disconnect the LAN port and try to use the integrated wireless:
```
ifname=wlan0
wlan_ssid=<SSID>
wlan_psk=<WPA-PSK>
```

**Comment by mike632t** [comment]
It stops - I'll give the intergrated wireless a go in a minute

**Comment by mike632t** [comment]
Managed to get 2.0.1 working - and discovered a base install really is basic!!

Thanks for your help

**Comment by FooDeas** [comment]
What was the reason?

**Comment by mike632t** [comment]
Succesfully completed a minimal install - but shutdown, reboot halt and poweroff are 'missing' intentional..?

**Comment by mike632t** [comment]
Still don't know why it worked..  (used a different subnet) but that can't be the reason!

**Comment by Mausy5043** [comment]
I've observed some peculiarities with `raspberrypi.org` too lately. Switching off DNSSEC on my DNS seemed to fix it.

**Comment by FooDeas** [comment]
It would be nice if the raspberrypi.org repository would have some official mirrors. 9 of 10 problems are caused by downtime, load or inconsistencies (sometimes caused by my proxy, too).
I've set up an "apt-cacher-ng" instance on another pi to catch most of them. Very useful if needed often.

**Comment by mike632t** [comment]
Think the problem I was having was as a result of DNS issues when looking up mirrordirector.raspbian.org - it may have been redirecting to domain my firewall doesn't link, but as I use dnsmasq to redirect them to my loopback address I don't think it is logged anywhere!

**Comment by Mausy5043** [comment]
@mike632t : you might want to add `log-queries` and optionally `log-dhcp` to your `dnsmasq` config file.

**Comment by mike632t** [comment]
Thanks - I've updated /etc/dnsmasq.conf (uncommented the existing line)

**Comment by FooDeas** [comment]
I have the same problem today: Hanging on the kernel download.
And it can't be a DNS issue. I checked that using the 8er DNS server.

**Comment by mike632t** [comment]
Glad it isn't just me!!  Unfortunatly I'm no closer to working out what it might be as there was nothing in my dnsmasq logs.

**Comment by FooDeas** [comment]
Download freezed at 23MB.
Successfully tried again two hours later.

**Comment by Mausy5043** [comment]
I'm almost sure that these problems will be much less after 02JAN2018.

**Comment by FooDeas** [comment]
My experience from today:
5 fails in a row. 1 "success" with issues at (kernel) boot. Similar to that what @mike632t reported [here](https://github.com/FooDeas/raspberrypi-ua-netinst/issues/120#issuecomment-354503055).

My "analysis":
I disabled my transparent proxy: 5 successes in a row
I re-enabled the transparent proxy: stuck at downloading kernel...
I re-enabled my apt-cacher-ng (with proxy): success

It's reproducible with all versions.

**Comment by mike632t** [comment]
Which proxy are you using..?

**Comment by FooDeas** [comment]
Squid

**Comment by eLvErDe** [comment]
@FooDeas again you're live saver. I experencied the same insane shit, raspberrypi-kernel stuck downloading when going throught Squid 3.5 (CentOS 7). It worked after changing config to use apt-cacher-ng instead of Squid.

**Comment by mike632t** [comment]
Same problem again with buster - but this is the only time I have an issue installing Debian from behind my firewall. A direct conenction to my router solved the problem (again), might be worth mentioning in a readme...?
