### ISSUE TITLE
P3 / Pi Zero W doesn't boot with cmdline kgdboc=serial0

### ISSUE THREAD

**Issue by mike632t** [FooDeas/raspberrypi-ua-netinst#122]
Install completes successfully on both, but when the reboot the green LED just flashes breifly and nothing else happens.  (I suspect that some firmware / kernel modules may be missing)

Both installations boot normally on a Pi 2 B.

See attached logs below (sorry it took so long to update my post - bit busy  this week!)
[installer-config.txt](https://github.com/FooDeas/raspberrypi-ua-netinst/files/1604643/installer-config.txt)
[config.txt](https://github.com/FooDeas/raspberrypi-ua-netinst/files/1604644/config.txt)
[cmdline.txt](https://github.com/FooDeas/raspberrypi-ua-netinst/files/1604646/cmdline.txt)

**Comment by FooDeas** [comment]
I'm afraid that this is not version related. I had that yesterday before I solved my connection problems. Confirmed with the last two versions, too.
I disabled my transparent proxy and things were working as expected. Successfully tested with my Pi3 and Zero multiple times.

**Comment by mike632t** [comment]
As I suspected - is it fixable (using the Pi 2 B?).  I'm assuming that one or more packages didn;t download

**Comment by FooDeas** [comment]
logfile?

**Comment by FooDeas** [comment]
Or you can try to setup apt-cacher-ng.

**Comment by FooDeas** [comment]
Interesting info:

> AIUI the raspberry pi foundation repo serves small files directly but under some circumstances redirects large files to a third party CDN.

[Source](https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=83491&sid=4dba589a74e405c009a90a54d8c0c626&start=50#p1153085)

This explains why the problems only occur on two packages.

**Comment by FooDeas** [comment]
I'm testing the following solution using a mirror I finally found:

Create the file "/raspberrypi-ua-netinst/config/apt/raspberrypi.org.list". Content:
`deb http://mirrors.ustc.edu.cn/archive.raspberrypi.org/debian __RELEASE__ main`

Stopped after downloading. I'll have another look at it tomorrow...

**Comment by mike632t** [comment]
Did some more testing normally I enable the uart as I only use the serial console - when I do this the LED on my Pi zero flashes breifly and it doesn't boot - if I don't enable the UART the LED flashes beifly then stays on...  I suspect it is booting (or starting to) but I can;t find it on my network!

**Comment by FooDeas** [comment]
Could you attach your `installer-config.txt` and post exactly what you customized too (config.txt, cmdline.txt, ...)?

**Comment by mike632t** [comment]
Added logs and config files to post

**Comment by FooDeas** [comment]
Try this:

**config.txt**
Use installer **default** file without any changes.

**cmdline.txt**
`dwc_otg.lpm_enable=0 consoleblank=0 console=serial0,115200 elevator=deadline rootwait` (nothing else)

**installer-config**
Use yours but **remove** the `cmdline` setting.

(The UART console should still work.)

**Comment by mike632t** [comment]
Don't I neet to use enable_uart=1 for the serial console on the Pi Zero to work?

**Comment by mike632t** [comment]
As I was beginning to suspect the problem is something to do with the enable_uart setting.

I now have a HDMI - VGA adapter so I was able to repeat the install on a Pi3, but this time I modified config.txt and cmdline.txt so that when it booted it used the standard console.

Initially with enable_uart=1 the Pi hung after ~0.3 seconds (kernel panic).  Powered down, changed config.txt so enable_uart=0 and tried again - success!!

So the question is what is missing to enable it to use the serial console...?

Note - The card also works just fine in a PiB and Pi 2B with the uart enabled

**Comment by FooDeas** [comment]
Related:
https://github.com/raspberrypi/firmware/issues/798

**Comment by FooDeas** [comment]
Just try the settings I posted above and report if the UART console is still working.

**Comment by mike632t** [comment]
Following the advise [in the related issue](https://github.com/raspberrypi/firmware/issues/798) I removed 'kgdboc=serial0,115200' from cmdline.txt and it works on both my Pi3 and Pi Zero W.

I still need to sort it out so I get the kernel messages on the console but basically I'm a very happy bunny!  I'm not sure how long it takes a Pi 3 to boot with a minimal install - but it isn't long!

**Comment by FooDeas** [comment]
Related: https://github.com/raspberrypi/linux/issues/2245
