### ISSUE TITLE
No /boot/raspberrypi-ua-netinst/ after installation

### ISSUE THREAD

**Issue by kraeml** [FooDeas/raspberrypi-ua-netinst#123]
I installed ua-netinst several times on PI3 but with the new version I couldn't found the file:

`/boot/raspberrypi-ua-netinst/reinstall/config.txt`

There is no dir `/boot/raspberrypi-ua-netinst/`

I this file gone? How to I reinstall ua-netinst 2.1.0?

**Comment by FooDeas** [comment]
~~I'm pretty sure, I missed that. Take the one from the installer zip.~~

**Comment by FooDeas** [comment]
Did you use the cleanup=1 setting in your config?

**Comment by mike632t** [comment]
cleanup=1
cleanup_logfiles=1

**Comment by FooDeas** [comment]
> cleanup=1
> cleanup_logfiles=1

The cleanup option removes **all** installer related files from the boot partition.
For a reinstallation you have to copy them to the SD card again.

**Comment by kraeml** [comment]
Yes, indeed. I will change this in my script into `cleanup_logfiles`.

Thanks for your help.
