### ISSUE TITLE
Installer fails on mkfs.vfat (devel branch)

### ISSUE THREAD

**Issue by dinosore** [FooDeas/raspberrypi-ua-netinst#127]
Using a 16GB sd card formatted as a single FAT32 partition, mkfs.vfat failed.

```
Waiting for /dev/mmcblk0... 
  Disk /dev/mmcblk0: 14.4 GiB, 15502147584 bytes, 30277632 sectors
  Disklabel type: dos
  Disk identifier: 0x4e42d3df
OK
Applying new partition table... OK
Initializing /boot as vfat... mkfs.fat: warning - lowercase labels might not work properly with DOS or Windows
mkfs.vfat: Too many clusters for filesystem - try more sectors per cluster
mkfs.fat 4.1 (2017-01-24)

Error: The installation could not be completed!
```
The log extract above is with the redirection to /dev/null removed.

Removing -s 1 fixed the problem.  I can't see why this should be - I suspect an mkfs bug.

Pull request follows.

**Comment by zejn** [comment]
One sector per cluster fixes an issue with RPi3 compute modules, see https://github.com/FooDeas/raspberrypi-ua-netinst/pull/125

Can you try adding "-v" to mkfs.vfat and then showing the output?

**Comment by zejn** [comment]
I created a test image with qemu-img and formatted it with mkfs.vfat, but I got no error. mkfs.vfat version seems to be the same.
```
# qemu-img create -f raw 16gb.img 15502147584 
Formatting '16gb.img', fmt=raw size=15502147584
# mkfs.vfat -v -s 1 16gb.img 
mkfs.fat 4.1 (2017-01-24)
Auto-selecting FAT32 for large filesystem
16gb.img has 255 heads and 63 sectors per track,
hidden sectors 0x0000;
logical sector size is 512,
using 0xf8 media descriptor, with 30277632 sectors;
drive number 0x80;
filesystem has 2 32-bit FATs and 1 sector per cluster.
FAT size is 232905 sectors, and provides 29811790 clusters.
There are 32 reserved sectors.
Volume ID is 232894a0, no volume label.
```

**Comment by FooDeas** [comment]
@dinosore Could you check it again against devel?

**Comment by dinosore** [comment]
Some sd card problems at the moment.  Will try again as soon as I can.

**Comment by dinosore** [comment]
I've updated my fork as per [b6cd12d  ](https://github.com/FooDeas/raspberrypi-ua-netinst/commit/b6cd12dcd12040d47c530fde502fd4b42fc51521) 

Haven't been able to test yet - hope to do so later today.

**Comment by dinosore** [comment]
I've tested and it works!

It might be better, though, not to suppress mkvs messages.  Your call.

**Comment by FooDeas** [comment]
Thanks a lot! I'll merge it soon.
