### ISSUE TITLE
Composite video

### ISSUE THREAD

**Issue by thijstriemstra** [FooDeas/raspberrypi-ua-netinst#133]
I have this LCD screen that requires the following settings in `/boot/config.txt`:

Disable `hdmi_force_hotplug` and enable `hdmi_ignore_hotplug`:

```
  # enable if hdmi display is not detected and composite is being output
  #hdmi_force_hotplug=1

  # uncomment to force composite output
  hdmi_ignore_hotplug=1
```
Set the screen width and height:
```
  # uncomment to force a console size. By default it will be display's size minus
  # overscan.
  framebuffer_width=320
  framebuffer_height=240
```
Enable the `disable_overscan` option:
```
  # uncomment this if your display has a black border of unused pixels visible
  # and your display can output without overscan
  disable_overscan=1
```

What settings would I use here? Note that there is a `hdmi_disable_overscan` option in raspberrypi-ua-netinst but `disable_overscan` is not hdmi-only and also used for composite.

Opened #136

**Comment by thijstriemstra** [comment]
I also need `display_rotate` to rotate or flip the screen orientation. The default value is 0, see https://www.raspberrypi.org/documentation/configuration/config-txt/video.md

**Comment by FooDeas** [comment]
I had a closer look on this today and I'm working on it.
Thanks for your PR! I'm starting with that and push a test version for you very soon.

**Comment by thijstriemstra** [comment]
Awesome, thanks @FooDeas.
