### ISSUE TITLE
No reboot, no shutdown commands with release=buster

### ISSUE THREAD

**Issue by Cryosim** [FooDeas/raspberrypi-ua-netinst#135]
reboot
-bash: reboot: command not found
shutdown -r now
-bash: shutdown: command not found
sudo /sbin/shutdown -r now
sudo: /sbin/shutdown: command not found
sudo /sbin/reboot
sudo: /sbin/reboot: command not found

My installer-config.txt:

To customize the raspberrypi-unattended-installer:

Place your settings in this file as described in the README.md or in the advanced documentation.
preset=minimal
release=buster
username=alex
userpw=***********
rootpw=*************
userperms_admin=1
timezone="Etc/GMT+3"
locales=en_US.UTF-8
system_default_locale=en_US.UTF-8
sound_enable=1
console_blank=180
ifname=eth1

**Comment by FooDeas** [comment]
release=buster?
Fix it and try again please.

**Comment by Cryosim** [comment]
Why? Buster avaliable. http://mirrordirector.raspbian.org/raspbian/dists/buster/

**Comment by FooDeas** [comment]
Buster is not released yet.
Unfortunately not supported.

**Comment by Cryosim** [comment]
OK. Can I install release Sid?

**Comment by FooDeas** [comment]
No. Same reason. But you can upgrade your stretch installation afterwards.

**Comment by Cryosim** [comment]
I install stretch. same issue.
Hit:1 http://archive.raspberrypi.org/debian stretch InRelease
Hit:2 http://mirrordirector.raspbian.org/raspbian stretch InRelease
Reading package lists... Done
reboot
-bash: reboot: command not found

shutdown -r
-bash: shutdown: command not found

/sbin/reboot
-bash: /sbin/reboot: No such file or directory

/sbin/shutdown
-bash: /sbin/shutdown: No such file or directory

sudo reboot
sudo: reboot: command not found

**Comment by Cryosim** [comment]
If I install base system, cannot connect via ssh

**Comment by FooDeas** [comment]
As you can see in the docs, there is no openssh-server in the base preset.

**Comment by FooDeas** [comment]
See #121, too.
