### ISSUE TITLE
Missing `cpio`

### ISSUE THREAD

**Issue by Mausy5043** [FooDeas/raspberrypi-ua-netinst#147]
Possibly related to #144:

After updating this morning using `apt` I'm now on kernel 4.14.30+ and find that I can nolonger succesfully complete a build on my Pies.

Apparently `cpio` is nolonger available:
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package cpio is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
   tar

E: Package 'cpio' has no installation candidate
```

`cpio` is required to [complete the build](https://github.com/FooDeas/raspberrypi-ua-netinst/search?utf8=%E2%9C%93&q=cpio&type=).

**Comment by Mausy5043** [comment]
Well blow me down! 😮 

`sudo apt update` fixed this.
I was convinced I'd done that.

**Comment by kpfleming** [comment]
I just ran into this as well, I did not have the `cpio` package installed. Apparently it's no longer part of the default installation in Stretch.

**Comment by kpfleming** [comment]
OK, that's good to know. Clearly then BUILD.md needs to tell the user to ensure that `cpio` is installed.
