### ISSUE TITLE
Add yourself to LICENSE

### ISSUE THREAD

**Issue by thijstriemstra** [FooDeas/raspberrypi-ua-netinst#16]
The LICENSE needs to be updated.

**Comment by FooDeas** [comment]
I'm not a lawyer and I'm not very familiar with self licensing.
But I know, I have to deploy the original license of the base and I do that with pleasure!
But also I think you may be right, that my modifications are unlicensed at this time and I would like to change this for the purpose of the base author and his original licensing purposes (free to use and more for everyone). If you could suggest a source or text, which is appropriate, I'd be thankful!

**Comment by thijstriemstra** [comment]
It's the MIT license and you can simply add your name with the copyright year.

**Comment by FooDeas** [comment]
Thanks @thijstriemstra! I didn't notice that. :laughing:

**Comment by thijstriemstra** [comment]
fyi: looks like github detects the license as 'ISC' which is very similar to the MIT license, e.g. https://gist.github.com/indexzero/10602128
