### ISSUE TITLE
Fails at "Copying boot files" on RPi version 1B 

### ISSUE THREAD

**Issue by markslater** [FooDeas/raspberrypi-ua-netinst#163]
I'm unable to get versions > 1.5.2 to work on my RPi 1B.

My understanding of what volumes are mounted at boot time is a bit shaky, but it appears to be a problem with insufficient space on `/tmp/bootfs`

I'm flashing the SD card like so:
```bash
wget -qO- https://github.com/FooDeas/raspberrypi-ua-netinst/releases/download/v2.2.1/raspberrypi-ua-netinst-v2.2.1.img.xz | xzcat - > /dev/mmcblk0
```

When I boot the RPi from the SD card, it stops with SOS quickly.  The error log on the SD card is as follows:

```
==================================================
raspberrypi-ua-netinst
==================================================
Revision v2.2.1 (1c98620)
Built on Mon Jul 30 20:22:39 CEST 2018
Running on Raspberry Pi version B
==================================================
https://github.com/FooDeas/raspberrypi-ua-netinst/
==================================================
Starting HWRNG... OK
Mounting boot partition... OK
Copying boot files... cp: error writing '/tmp/bootfs/start_x.elf': No space left on device

Error: The installation could not be completed!
```

For reference, here's what `cpuinfo` gives me on the Pi:
```bash
root@pi:~# cat /proc/cpuinfo
processor	: 0
model name	: ARMv6-compatible processor rev 7 (v6l)
BogoMIPS	: 697.95
Features	: half thumb fastmult vfp edsp java tls 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xb76
CPU revision	: 7

Hardware	: BCM2835
Revision	: 0002
```
Note that on version 1.5.2, the install succeeds, but only if I restrict the size of additional files I include - a 2 KB text file works fine, but a 5 MB jar causes it to fail in much the same way as above.  I tried altering the `bootsize` - both increasing (`bootsize=+256M`) and decreasing (`bootsize=+64M`), but no dice.

As I mentioned I don't really understand what volumes are available at that point in the script (I added a `df -h` to the script, but that fails... I assume this is because of where it is in the boot process), nor how to alter the size of the volume.

**Comment by FooDeas** [comment]
The installer runs out of memory before SD card initialization.
Do you use any special config?

**Comment by markslater** [comment]
No, just the vanilla 2.2.1 image flashed to the SD card.

I've just tried 2.1.0, and that seems to work fine.  However, vanilla 2.0.0 fails with an almost identical log to 2.2.1:

```bash
==================================================
raspberrypi-ua-netinst
==================================================
Revision v2.0.0 (84cbb40)
Built on Mon Oct 16 02:04:49 CEST 2017
Running on Raspberry Pi version B
==================================================
https://github.com/FooDeas/raspberrypi-ua-netinst/
==================================================
Starting HWRNG... OK
Mounting boot partition... OK
Copying boot files... cp: error writing '/bootfs/raspberrypi-ua-netinst/raspberrypi-ua-netinst.cpio.gz': No space left on device
cp: error writing '/bootfs/raspberrypi-ua-netinst/error-19700101T000010.log': No space left on device
cp: error writing '/bootfs/start.elf': No space left on device
cp: error writing '/bootfs/start_cd.elf': No space left on device
cp: error writing '/bootfs/start_db.elf': No space left on device
cp: error writing '/bootfs/start_x.elf': No space left on device

Error: The installation could not be completed!
```

**Comment by Mausy5043** [comment]
Could be a dud SD-card.

The 'vanilla' `bootsize` is 128M which is more than enough.

Installed on 18AUG2018:
```
$ df -h /boot
Filesystem      Size  Used Avail Use% Mounted on
/dev/mmcblk0p1  127M   22M  105M  18% /boot
```

**Comment by markslater** [comment]
Sorry for the delay in replying.

I don't think it's a dud SD card - if I put the card in a Pi Zero, it completes fine:
```bash
==================================================
raspberrypi-ua-netinst
==================================================
Revision v2.2.1 (1c98620)
Built on Mon Jul 30 20:22:39 CEST 2018
Running on Raspberry Pi version Zero
==================================================
https://github.com/FooDeas/raspberrypi-ua-netinst/
==================================================
[etc]
```
FWIW I'm loving the project, though I'm currently limited 2.1.0.

**Comment by mpmc** [comment]
I can confirm this, I dug out my old 1B and I'm now getting the the same error. 
```
==================================================
raspberrypi-ua-netinst
==================================================
Revision v2.2.1 (1c98620)
Built on Mon Jul 30 20:22:39 CEST 2018
Running on Raspberry Pi version B
==================================================
https://github.com/FooDeas/raspberrypi-ua-netinst/
==================================================
Starting HWRNG... OK
Mounting boot partition... OK
Copying boot files... cp: error writing '/tmp/bootfs/start_x.elf': No space left on device

Error: The installation could not be completed!
```

Checked SD card for errors, fine. Also ran in a zero, that ran fine!

Edit: as @markslater I used 2.1.0, that completed fine!

**Comment by FooDeas** [comment]
The old 256MB RAM model B gets out of memory...

**Comment by FooDeas** [comment]
I had to fake the low memory on my old 1B with 512MB. It should be fixed in devel branch now.
Please test and report!

**Comment by markslater** [comment]
Works like a charm.  Thanks!

**Comment by FooDeas** [comment]
Thank you! I'll release it.
