### ISSUE TITLE
Pi Zero*

### ISSUE THREAD

**Issue by mocallins** [FooDeas/raspberrypi-ua-netinst#170]
Am I to understand, this installer, should work with a Raspberry Pi Zero * ?

I've downloaded the installer.
Followed all instructions, but the Pi does not boot up, as I have seen it do with another image (Raspbian Stretch, on an 8GB card)
I am trying to use a 4GB card (of which I have a bagful) and none of them work ( I don';t blioeve that ALLL are defective), as well as the other 5 Pi's I have to work with.

I don't see any l;ogfile created on the sd card.

I am at a loss.

**Comment by FooDeas** [comment]
It definitely works on all Pi Zero models. Maybe you extracted into a subfolder or used a non FAT partition.

**Comment by mocallins** [comment]
Nope, root folder.Tried formatting with all FAT types, no luck.Edited installer-config.txt to specifically use the wifi interface, no help.
Is there any debug flag that can be turned on so we can see anything happening, or write to a log file, anything at all so i can give more info about what's going on ?
Thanks.
    On Sunday, May 26, 2019, 10:32:33 AM CDT, FooDeas <notifications@github.com> wrote:  
 
 
It definitely works on all Pi Zero models. Maybe you extracted into a subfolder or used a non FAT partition.

**Comment by FooDeas** [comment]
I'd check the following first in this order: Flashing activity LED? HDMI out? DHCP lease?

**Comment by mocallins** [comment]
Nope, no flashing led activity.
I have a little usb expansion hub attached, and it has an led on it as well, and it flash once at power on, then again about a second later, then nothing.Don't worry i've tried it without this hub as well.Don't receive that rainbow screen either.
And i know its a working Pi, have connected via the usb port test with my computer, and I hear the ding, for new device.Also have used an 8GB card and all works fine with that.Just cannot get it to work with these 4GB cards i have.

    On Sunday, May 26, 2019, 2:34:00 PM CDT, FooDeas <notifications@github.com> wrote:  
 
 
I'd check the following first in this order: Flashing activity LED? HDMI out? DHCP lease?

**Comment by FooDeas** [comment]
If the activity led doesn't show activity, it doesn't find the bootloader. Try to repartition the SD card properly.

**Comment by mocallins** [comment]
Properly ?
I've used SD Formatter. Windows drive format options, and any number of other formating tools I've found / suggested.

    On Sunday, May 26, 2019, 3:10:31 PM CDT, FooDeas <notifications@github.com> wrote:  
 
 
If the activity led doesn't show activity, it doesn't find the bootloader. Try to repartition the SD card properly.

**Comment by FooDeas** [comment]
Then last idea:
Copy the content of the fat partition from your working 8GB card to the 4GB card and check if that shows any activity.

**Comment by mocallins** [comment]
Sure, I'm game for anything, at this point, lol


    On Sunday, May 26, 2019, 3:18:44 PM CDT, FooDeas <notifications@github.com> wrote:  
 
 
Then last idea:
Copy the content of the fat partition from your working 8GB card to the 4GB card and check if that shows any activity.

**Comment by mocallins** [comment]
I was also gonna tell you, that I've gone to the point of using a multifunction card reader, just to eliminate having to put the micro card in its larger adapter, no help, smh.

    On Sunday, May 26, 2019, 3:18:44 PM CDT, FooDeas <notifications@github.com> wrote:  
 
 
Then last idea:
Copy the content of the fat partition from your working 8GB card to the 4GB card and check if that shows any activity.

**Comment by FooDeas** [comment]
You prooved that the cards are the problem...

**Comment by mocallins** [comment]
Sorry I responded while I was in the process, just as an ennectdote.
Didn't work.And as a goof I put the 8GB card in there and it of course booted.


    On Sunday, May 26, 2019, 3:39:20 PM CDT, FooDeas <notifications@github.com> wrote:  
 
 
You prooved that the cards are the problem...

**Comment by FooDeas** [comment]
I can't help you with these cards. Maybe you could check them with [Check Flash for Windows](http://mikelab.kiev.ua/index_en.php?page=PROGRAMS/chkflsh_en) or similar and face your seller with the probably bad results.
