### ISSUE TITLE
could not download deb 10 u1 armhf.deb

### ISSUE THREAD

**Issue by uplamartya** [FooDeas/raspberrypi-ua-netinst#181]
![644ad583-28ac-4f2c-b481-5d6e929fcdb9](https://user-images.githubusercontent.com/47631015/65936659-ec95ff00-e43a-11e9-800e-5714aabd5738.jpeg)

Kindly provide any solution. using 3B+

LOGFILE->

==================================================
raspberrypi-ua-netinst
==================================================
Revision v2.4.0 (5dfae25)
Built on Sun Aug 11 22:07:31 CEST 2019
Running on Raspberry Pi version 3 Model B+
==================================================
https://github.com/FooDeas/raspberrypi-ua-netinst/
==================================================
Remounting TempFS... OK
Mounting boot partition... OK
Copying boot files... OK
Executing installer-config.txt...
OK

Searching for deprecated variables...

Checking if config.txt needs to be modified before starting installation...
  Setting HDMI options... OK
OK

Unmounting boot partition... OK

Network configuration:
  ifname = eth0
  ip_addr = dhcp
  online_config = 

Waiting for eth0... OK
Configuring eth0 with DHCP... 192.168.100.138
Printing console to telnet output started.
Set time using ntpdate... OK

Installation started at Tue Oct  1 05:20:52 UTC 2019 (UTC).

Resulting installer configuration:
  preset = server
  packages = nano
  firmware_packages = 1
  mirror = http://mirrordirector.raspbian.org/raspbian/
  mirror_cache = 
  release = buster
  hostname = pi
  domainname = 
  user_ssh_pubkey = 
  root_ssh_pubkey = 
  root_ssh_pwlogin = 0
  ssh_pwlogin = 
  username = root
  usergpio = 
  usergpu = 1
  usergroups = 
  usersysgroups = 
  userperms_admin = 1
  userperms_sound = 0
  cdebootstrap_cmdline = --flavour=minimal --include=locales,kmod,libpam-systemd,rng-tools,cpufrequtils,ifupdown,net-tools,openssh-server,dosfstools,fake-hwclock,vim-tiny,iputils-ping,wget,ca-certificates,rsyslog,cron,dialog,locales,tzdata,less,man-db,logrotate,bash-completion,console-setup,apt-utils,systemd-sysv,sudo,isc-dhcp-client
  packages_postinstall = firmware-atheros,firmware-brcm80211,firmware-libertas,firmware-misc-nonfree,firmware-realtek,nano,raspberrypi-bootloader,raspberrypi-kernel,raspberrypi-sys-mods,libraspberrypi-bin,raspi-copies-and-fills
  boot_volume_label = 
  root_volume_label = 
  bootsize = +128M
  bootoffset = 8192
  rootsize = 
  timeserver = time.nist.gov
  timezone = Asia/Kolkata
  rtc = 
  dt_overlays = 
  keyboard_layout = us
  locales = en_US
  system_default_locale = en_US
  wlan_country = 
  ip_ipv6 = 1
  cmdline = dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 elevator=deadline fsck.repair=yes
  drivers_to_load = 
  gpu_mem = 32
  console_blank = 
  hdmi_type = 
  hdmi_tv_res = 1080p
  hdmi_monitor_res = 1024x768
  hdmi_disable_overscan = 0
  hdmi_system_only = 0
  usbroot = 0
  usbboot = 0
  rootdev = /dev/mmcblk0
  rootpartition = /dev/mmcblk0p2
  rootfstype = f2fs
  rootfs_mkfs_options = -f
  rootfs_install_mount_options = noatime
  rootfs_mount_options = noatime
  final_action = reboot
  quiet_boot = 0
  disable_raspberries = 0
  disable_splash = 0
  cleanup = 0
  cleanup_logfiles = 0
  spi_enable = 0
  i2c_enable = 0
  i2c_baudrate = 
  sound_enable = 0
  sound_usb_enable = 0
  sound_usb_first = 0
  camera_enable = 0
  camera_disable_led = 0

OTP dump:
  16:00280000
  17:3020000a
  18:3020000a
  27:00001f1f
  28:efb726ba
  29:1048d945
  30:00a020d3
  66:02009eaa

Waiting 5 seconds.....
Waiting for /dev/mmcblk0... 
  Disk /dev/mmcblk0: 7.4 GiB, 7948206080 bytes, 15523840 sectors
  Disklabel type: dos
  Disk identifier: 0x1ad7461a
OK
Applying new partition table... OK
Initializing /boot as vfat... OK
Copying /boot files in... OK
Initializing / as f2fs...   
  	F2FS-tools: mkfs.f2fs Ver: 1.11.0 (2018-07-10)
  
  Info: Disable heap-based policy
  Info: Debug level = 0
  Info: Label = 
  Info: Trim is enabled
  Info: Segments per section = 1
  Info: Sections per zone = 1
  Info: sector size = 512
  Info: total sectors = 15253504 (7448 MB)
  Info: zone aligned segment0 blkaddr: 512
  Info: format version with
    "Linux version 4.19.58-v7+ (dom@buildbot) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611)) #1245 SMP Fri Jul 12 17:25:51 BST 2019"
  Info: [/dev/mmcblk0p2] Discarding device
  Info: This device doesn't support BLKSECDISCARD
  Info: Discarded 7448 MB
  Info: Overprovision ratio = 2.330%
  Info: Overprovision segments = 176 (GC reserved = 93)
  Info: format successful
OK
Mounting new filesystems... OK
Starting HWRNG... OK

Starting install process...
  P: Retrieving Release
  P: Retrieving Release.gpg
  P: Validating Release
  I: Good signature from "Mike Thompson (Raspberry Pi Debian armhf ARMv6+VFP) <mpthompson@gmail.com>"
  P: Parsing Release
  P: Retrieving Packages.xz
  P: Validating Packages.xz
  P: Parsing Packages
  P: Retrieving gcc-8-base
  P: Validating gcc-8-base
  P: Retrieving libgcc1
  P: Validating libgcc1
  P: Retrieving libc6
  P: Validating libc6
  P: Retrieving libbz2-1.0
**  E: Couldn't download pool/main/b/bzip2/libbz2-1.0_1.0.6-9.2~deb10u1_armhf.deb!**

  ERROR: 1, trying again (2/5)...
  P: Retrieving Release
  P: Retrieving Release.gpg
  P: Validating Release
  I: Good signature from "Mike Thompson (Raspberry Pi Debian armhf ARMv6+VFP) <mpthompson@gmail.com>"
  P: Parsing Release
  P: Validating Packages
  P: Parsing Packages
  P: Validating gcc-8-base
  P: Validating libgcc1
  P: Validating libc6
  P: Retrieving libbz2-1.0
  P: Validating libbz2-1.0
  P: Retrieving liblzma5
 ** E: Couldn't download pool/main/x/xz-utils/liblzma5_5.2.4-1_armhf.deb! **

  ERROR: 1, trying again (3/5)...
  P: Retrieving Release
  P: Retrieving Release.gpg
  P: Validating Release
  I: Good signature from "Mike Thompson (Raspberry Pi Debian armhf ARMv6+VFP) <mpthompson@gmail.com>"
  P: Parsing Release
  P: Validating Packages
  P: Parsing Packages
  P: Validating gcc-8-base
  P: Validating libgcc1
  P: Validating libc6
  P: Validating libbz2-1.0
  P: Retrieving liblzma5
  P: Validating liblzma5
  P: Retrieving libpcre3
  P: Validating libpcre3
  P: Retrieving libselinux1
  P: Validating libselinux1
  P: Retrieving zlib1g
  P: Validating zlib1g
  P: Retrieving libattr1
**  E: Couldn't download pool/main/a/attr/libattr1_2.4.48-4_armhf.deb! **

  ERROR: 1, trying again (4/5)...
  P: Retrieving Release
  P: Retrieving Release.gpg
  P: Validating Release
  I: Good signature from "Mike Thompson (Raspberry Pi Debian armhf ARMv6+VFP) <mpthompson@gmail.com>"
  P: Parsing Release
  P: Validating Packages
  P: Parsing Packages
  P: Validating gcc-8-base
  P: Validating libgcc1
  P: Validating libc6
  P: Validating libbz2-1.0
  P: Validating liblzma5
  P: Validating libpcre3
  P: Validating libselinux1
  P: Validating zlib1g
  P: Retrieving libattr1
  P: Validating libattr1
  P: Retrieving libacl1
  P: Validating libacl1
  P: Retrieving tar
**  E: Couldn't download pool/main/t/tar/tar_1.30+dfsg-6_armhf.deb! **

  ERROR: 1, trying again (5/5)...
  P: Retrieving Release
  P: Retrieving Release.gpg
  P: Validating Release
  I: Good signature from "Mike Thompson (Raspberry Pi Debian armhf ARMv6+VFP) <mpthompson@gmail.com>"
  P: Parsing Release
  P: Validating Packages
  P: Parsing Packages
  P: Validating gcc-8-base
  P: Validating libgcc1
  P: Validating libc6
  P: Validating libbz2-1.0
  P: Validating liblzma5
  P: Validating libpcre3
  P: Validating libselinux1
  P: Validating zlib1g
  P: Validating libattr1
  P: Validating libacl1
  P: Retrieving tar
 ** E: Couldn't download pool/main/t/tar/tar_1.30+dfsg-6_armhf.deb! **

  ERROR: 1

Error: The installation could not be completed!

**Comment by Mausy5043** [comment]
Could be congestion at the server. Have you tried it again at a later time?

"If at first you don't succeed..." ;-)

**Comment by uplamartya** [comment]
> Could be congestion at the server. Have you tried it again at a later time?
> 
> "If at first you don't succeed..." ;-)

Multiple times . Every time i got the same error

**Comment by FooDeas** [comment]
It is a connection or server problem. Set installer_pkg_downloadretries to a high value that allows more retries instead of 5.

**Comment by uplamartya** [comment]
@FooDeas , ok thanks. Will let you know after trying this .
