### ISSUE TITLE
Questions about DHCP

### ISSUE THREAD

**Issue by ghost** [FooDeas/raspberrypi-ua-netinst#182]
Just a few newbees questions about DHCP handling:

as I understood, in this unattended installation toolset DHCP will be handled with dhclient from the isc-dhcp-client package. -- Correct ?

When I install raspbian with the official image, DHCP will be handled by dhcpcd. -- Correct ?

Also raspi-config seems to require dhcpcd, as the setting "wait for network on boot" is creating a file (/etc/systemd/system/dhcpcd.service.d/wait.conf) that has an ExecStart to /usr/lib/dhcpcd5/dhcpcd and so will be interpreted by dhcpcd.

So what could be the reason(s) to use isc-dhcp-client ?

Is there a solution for "wait for network on boot" with dhclient ?

**Comment by FooDeas** [comment]
isc-dhcp-client is the "default" debian package.
There are multiple ways to get this working as you want.
