### ISSUE TITLE
Disable automatic update 

### ISSUE THREAD

**Issue by mike632t** [FooDeas/raspberrypi-ua-netinst#183]
How do I prevent the installer from updating the (already installed) packages at the end?  

The actual installation appears to work but the process hangs when updating the system at the end..

Raspberry Pi 3B repeatidly hangs installing wireless-regdb when installing using wifi (tried three times), testing using eth0 now.  (Expect it is the mirror that is the problem, but it would be nice to be able to skip the upgrade to work around this issue as it keeps happening!)

I like some of the 'new' installer features BTW.

Thanks

**Comment by FooDeas** [comment]
Please post your model.
I start the next test and development cycle this week.

**Comment by mike632t** [comment]
Does the installer pull the packeges to be installed from the same repository/server as the system does when it is doing the updates?

Thanks

**Comment by FooDeas** [comment]
Yes it does.

**Comment by kpfleming** [comment]
It pulls from the same URL, but that's usually mirrordirector.raspbian.org so each individual package download may come from a different server.
