### ISSUE TITLE
Using other images

### ISSUE THREAD

**Issue by LeonHoeppner** [FooDeas/raspberrypi-ua-netinst#185]
Hi,

is it possible to use custom/antother images like this one: http://emanual.robotis.com/docs/en/platform/turtlebot3/raspberry_pi_3_setup/#install-linux-based-on-raspbian
And if so, where do i have do change it?

Kind regards.

**Comment by FooDeas** [comment]
The installer is not image based but works with packages.
You just have to find out, which packages/files you need and add the them together with the repository description.
