### ISSUE TITLE
missing /etc/services

### ISSUE THREAD

**Issue by AlienDiva** [FooDeas/raspberrypi-ua-netinst#187]
Package "netbase" provides /etc/services which is empty and caused some headaches with NFS
Please consider netbase as one of the default packages, it's a tiny but critical package.

Thank-you by the way to all contributors for the great work, very easy install on RPI Zero W.

**Comment by Mausy5043** [comment]
`netbase` *does* get installed with the `preset=server` option.

Which `preset` are you using?
