### ISSUE TITLE
Install files feature.

### ISSUE THREAD

**Issue by mocallins** [FooDeas/raspberrypi-ua-netinst#191]
Is the installer supposed to copy the files from  ..\config\files\root\accordng-to-install_files.list ?

I've looked in multiple places, they only seem to reside in /boot/* on the trget system.

Thanks

**Comment by kpfleming** [comment]
The `.list` file goes into config/files; the files to be copied go into config/file/root (and further subdirectories based on the locations they should be copied into). You have to tell the installer which files you want copied, and their owner/group and permissions, which you do by creating the `.list` file.

**Comment by mocallins** [comment]
Yep, i think i did all that, files don't get copied.

**Comment by FooDeas** [comment]
Attach/post your "accordng-to-install_files.list" and post the exact location of one of your files.

**Comment by mocallins** [comment]
![image](https://user-images.githubusercontent.com/1242690/79083537-7e3cce00-7cf4-11ea-9e76-3551b3062798.png)

![image](https://user-images.githubusercontent.com/1242690/79083574-b0e6c680-7cf4-11ea-9380-2e31ca59ec5c.png)

![image](https://user-images.githubusercontent.com/1242690/79083601-ea1f3680-7cf4-11ea-9af8-1cbb8fe0b11b.png)

**Comment by kpfleming** [comment]
Do you have your editor (ConTEXT) configured to produce Unix line endings instead of Windows line endings? If not that could be a problem.

Also, after the installation is complete you can look at the log file in the /boot directory to see what happened during the installation, you should be able to find the section towards the end where the install_files.list file was opened and processed.

**Comment by mocallins** [comment]
I just checked and changed that file, in my editor, to use unix (LF), it was  dos (crlf)  :~
can i just run again as a reinstall ? or have to  redo the whole thing ?

    On Sunday, April 12, 2020, 7:45:47 PM CDT, Kevin P. Fleming <notifications@github.com> wrote:  
 
 


Do you have your editor (ConTEXT) configured to produce Unix line endings instead of Windows line endings? If not that could be a problem.

Also, after the installation is complete you can look at the log file in the /boot directory to see what happened during the installation, you should be able to find the section towards the end where the install_files.list file was opened and processed.

**Comment by mocallins** [comment]
Also, does netinst contain all the other firmware-netcard-package, so the it can recognize any supported adapter, or is that possible ?

Any future enhancements to change the shell, i like to use tcsh ?

**Comment by FooDeas** [comment]
<img width="185" alt="hone" src="https://user-images.githubusercontent.com/20836734/79119378-80ed0100-7d90-11ea-8761-dec8ad5f21ee.png">
Mystery solved?

**Comment by mocallins** [comment]
AAaaarrrrgggghhhh, yep you're right, gaaahhh, sorry about that.
