### ISSUE TITLE
Raspberry Pi 3B Error - Kernel version "4.19.97-v7+" could not be found. 

### ISSUE THREAD

**Issue by unclehowell** [FooDeas/raspberrypi-ua-netinst#192]
UA-NETINST Works fine on the Raspberry Pi4, but I want to create an image which will work on both the RPI3 and RPI4. However, no matter what I try, I keep getting this error on the Raspberry Pi 3 (B). Even when I scrub all the Raspberry Pi4 config and just focus on trying to get this to work on the Raspberry Pi 3B, I keep arriving at this error. The killer is, I have to go through the 20 minute process every time just to see this error again and again. What's the solution please ? 

Kernel modules for the kernel version "4.19.97-v7+" could not be found. Searching for alternatives...
  Using modules of kernel version "4.19.58-v7+".
modprobe: can't load module rfkill (kernel/net/rfkill/rfkill.ko): invalid module format
Waiting for wlan0... 1.. 2.. 3.. 4.. 5.. 6.. 7.. 8.. 9.. 10.. 11.. 12.. 13.. 14.. 15.. 16.. 17.. 18.. 19.. 20.. 21.. 22.. 23.. 24.. 25.. 26.. 27.. 28>

Error: The installation could not be completed!

**Comment by FooDeas** [comment]
Please use the current release with the updated kernels and report.

**Comment by unclehowell** [comment]
The one just posted an hour ago? Will do. Thanks. Yes its working. Excellent
