### ISSUE TITLE
Raspberry PI2 stucks in Configuring eth0 with DHCP

### ISSUE THREAD

**Issue by TFTomSun** [FooDeas/raspberrypi-ua-netinst#196]
I tried to install a PI2 two times. The first time went fine, during the second installation (another sd card) the PI hangs at the message:

```
Configuring eth0 with DHCP
```

and doesn't continue with the installation.

Any ideas what could be the reason?

**Comment by TFTomSun** [comment]
I could solve the issue, by resetting the name that my router assigned to the mac of the pi. I don't know if its an issue on the routers side or in the PI, therefore I leave the issue open.

**Comment by FooDeas** [comment]
Wasn't reproducible.
