### ISSUE TITLE
Installer not booting anymore

### ISSUE THREAD

**Issue by Mausy5043** [FooDeas/raspberrypi-ua-netinst#199]
Recent builds (as far as I can tell since the past few days) do not produce a bootable builder anymore.
The only error I see during the build is this one:

```
cp: cannot stat 'tmp/lib/modules/5.4.51-v7+/kernel/drivers/hwmon/hwmon.ko': No such file or directory
```

Any ideas where I might need to start looking?

PS: I'm building the installer from the `devel` branch.

**Comment by FooDeas** [comment]
Seems to be a changed package content.
Update and build hast to be checked. I can do that next week.

**Comment by kpfleming** [comment]
Yes, there was a major kernel change (from 4.19 to 5.4) this week.

**Comment by Mausy5043** [comment]
OK thanks.
To provide you with a bit more info, although I think it wont add a lot, I've managed to get one of the Pi's hooked up to a screen and get a screenshot of the attempted boot.

https://photos.app.goo.gl/95FrM14AZQ7cymL59

EDIT: It does indeed seem to be a 5.4.51-v7+ kernel (thanks @kpfleming for pointing that out)

**Comment by Mausy5043** [comment]
> Seems to be a changed package content.
> Update and build hast to be checked. I can do that next week.

Thanks. would appreciate that very much.

**Comment by FooDeas** [comment]
It is time to develop an automatic resolution of package dependencies and file/link handling.
I hope this will not add too much unnecessary content...

**Comment by Mausy5043** [comment]
I tried building using ```master``` but that doesn't work either.

**Comment by Mausy5043** [comment]
A new build is still running, but I'm confident that patch #200 works.
Please review & commit.

EDIT: Build was successful. Installed system is up and running.

**Comment by FooDeas** [comment]
Thank you! I'm still at scripting the dependency solver. It's horrible...
