### ISSUE TITLE
Testing on Zero

### ISSUE THREAD

**Issue by Phiber2000** [FooDeas/raspberrypi-ua-netinst#2]
Does someone have a RaspberriPi Zero to test the netinstaller on it using a USB network adapter?

**Comment by Phiber2000** [comment]
Please post if it boots the kernel (no rainbow screen) and the network chipset you tried.

**Comment by thijstriemstra** [comment]
Where you located, I can sponsor one for you @Phiber2000 (or is it @FooDeas :)).

**Comment by FooDeas** [comment]
Phiber2000 was a university classmate and transferred me the ownership of this repository because I always used his GitHub account. :smile:
I'm from Germany and wouldn't say no.

**Comment by thijstriemstra** [comment]
cool, I sent you an email at your github commit email address.

**Comment by FooDeas** [comment]
No email received yet - typo?

**Comment by thijstriemstra** [comment]
It's your username ending with aeberlein.de correct?

**Comment by FooDeas** [comment]
Absolutely: foodeas@aeberlein.de

**Comment by thijstriemstra** [comment]
I've resent it, weird..

**Comment by FooDeas** [comment]
I see why:
`reject: RCPT from unknown[166.78.137.222]: 450 4.7.1 Client host rejected: cannot find your reverse hostname, [166.78.137.222]; from=<info@collab.nl> to=<foodeas@...> proto=ESMTP helo=<mail.collab.nl>`

Weird too: The mailserver IP is located in "San Antonio, Texas, United States" :D
Could you use another mail account? The server you sent from is not configured correctly.

**Comment by thijstriemstra** [comment]
damn, i have to fix that. But yea the servers in the us. I'll use gmail sigh.

**Comment by FooDeas** [comment]
Did you receive my answer?

**Comment by FooDeas** [comment]
Thanks to @thijstriemstra for the donation!
Running the Zero with an USB ethernet adapter, I found a bug belonging to the kernel modules and here is the result:

```
==================================================
raspberrypi-ua-netinst
==================================================
Revision 93f302b
Built on Tue Sep 13 20:36:21 CEST 2016
Running on Raspberry Pi version Zero
==================================================
https://github.com/FooDeas/raspberrypi-ua-netinst/
==================================================
Starting HWRNG succeeded!
Copying boot files... OK
=================================================
=== Start executing installer-config.txt. ===
=== Finished executing installer-config.txt. ===
=================================================

Network configuration:
  ip_addr = dhcp
  online_config = 

Loading additional drivers.
 Loading driver 'ax88179_178a'... OK
Finished loading additional drivers

Waiting for eth0... OK
Configuring eth0 with DHCP... 192.168.1.1
Time set using ntpdate to... Tue Sep 13 18:39:29 UTC 2016
...
```

:+1::+1::+1::+1::+1::+1:

There are two possibilities to get the Zero working:

**Variant 1:**
- You need a USB ethernet adapter, which is supported by the current kernel.
- ~~Connect the USB ethernet adapter to a running Debian linux and note the appropriate kernel module via `lsmod`.~~
- ~~Add `drivers_to_load=<kernel module>` to the `installer-config.txt`.~~
- Connect the USB ethernet adapter and proceed as it would be onboard.  
  This will be supported from v1.3.0.

**Variant 2:**
- Use any other Raspberry Pi with µSD slot for netinstall.
- Just insert the µSD card from the other Raspberry Pi after the installation. It will be fully compatible!
