### ISSUE TITLE
Auto pair bluetooth device(s)

### ISSUE THREAD

**Issue by thijstriemstra** [FooDeas/raspberrypi-ua-netinst#20]
I have a bluetooth keyboard that I'd like to pair by default. Is this maybe something for a config setting, a list of bluetooth identifiers or something that are trusted by default? I haven't looked into the whole bluetooth support yet but maybe someone tried doing this before.

**Comment by FooDeas** [comment]
BT pairing needs communication in both directions. So the first time you connect, often it won't be done by modifying a config file on one side only.
Scripting in post-install would be possible because I activate the BT on Pi3 during installation process.

**Comment by thijstriemstra** [comment]
I'm not able to list the internal bluetooth device for a RPi3, e.g.:

```
$ hcitool scan
Device is not available: No such device
```

Installed following packages after some searching:

```
bluez,bluetooth,raspberrypi-sys-mods,pi-bluetooth,libbluetooth3,libbluetooth-dev,libdbus-c++-dev,libdbus-1-dev
```

Also added user to bluetooth group as suggested [here](https://www.pi-supply.com/make/fix-raspberry-pi-3-bluetooth-issues/):

```
sudo usermod -G bluetooth -a pi
```

But still not working. Any idea?

**Comment by FooDeas** [comment]
I'm working on it at the moment and got it working. Please be patient until the new release in about 12 hours.

**Comment by FooDeas** [comment]
To get BT and UART working on model 3B at the same time was a bit tricky.
It's fixed and tested with ~~b2986a416d1bc19188153ea966721ab83b1d1eae~~ b40f6ff.

I changed `config.txt` and `udev` rules to get it fully compatible with all packages and now exactly behaves like you would use a common raspbian image.
(UART is on `/dev/serial0;` BT on `/dev/serial1` as expected)

Short hint: All packages you need are installed with `apt-get install pi-bluetooth`. No further changes needed to get it work.

**Comment by thijstriemstra** [comment]
Cool, I'll test it now. I saw you removed the GPIO udev rule, I suppose it's still working without that? Update: yes it does.

**Comment by thijstriemstra** [comment]
Awesome it works now:

```
$ hcitool dev
Devices:
    hci0    B8:27:EB:E4:20:75
```

**Comment by FooDeas** [comment]
For your information:
The GPIO rule I added to get #8 working, was removed because the package `raspberrypi-sys-mods` is installed by default now. It delivers another rule which does the same and gets updates if available.
