### ISSUE TITLE
Error during install (/proc/sys/kernel/hotplug)

### ISSUE THREAD

**Issue by Mausy5043** [FooDeas/raspberrypi-ua-netinst#201]
https://github.com/FooDeas/raspberrypi-ua-netinst/blob/0acc6e1d0ccca1f240c33d83f379c012a389e719/scripts/opt/raspberrypi-ua-netinst/install.sh#L542

This line throws an error during booting of the installer (copied from the screen): 
```
/opt/raspberrypi-ua-netinst/install.sh  line 542: /proc/sys/kernel/hotplug  No such file or directory
```

BTW, the install completed successfully. :-\

**Comment by FooDeas** [comment]
I can't reproduce this with the current v2.5.0 anymore.
