### ISSUE TITLE
no space left on 1GB SD card

### ISSUE THREAD

**Issue by ikino** [FooDeas/raspberrypi-ua-netinst#202]
Hello,
I try install it on 1GB sd card, but no space left error appears. You wrote so 1gb is enough, on readme. Where is problem?

**Comment by Mausy5043** [comment]
Could you please provide some context?   
When does this error occur?   
Would you mind sharing the `installer-config.txt` and the `post-install.txt` files you used?

**Comment by FooDeas** [comment]
Because of upcoming major changes, the minimum storage size will presumably rise in the upcoming release.
