### ISSUE TITLE
Adapt the install script for Raspi4 USB mass storage boot, and regenerate the image

### ISSUE THREAD

**Issue by rainbowbreeze** [FooDeas/raspberrypi-ua-netinst#206]
I'm trying to use the installer with a Raspberry 4B, and I want to install and run the OS on a SSD drive connected to USB (no SD card inserted).

Before September 2020, the process was complex and not all the SSD were supporter, but after September, a change in the Raspi4 EEPROM simplified a lot the process ([source](https://www.raspberrypi.org/documentation/hardware/raspberrypi/bootmodes/msd.md))

The current raspberrypi-ua-netinst release v2.4.0+ (caf7423), only takes into account the USB mass storage boot for devices up to Raspi3B.

In fact:
- I had to manually run update.sh script to download latest .elf .img and .dat files, with a kernel supporting these EEPROM changes and more updated drivers for wifi
- I created a new release of raspberrypi-ua-netinst, using the build.sh script, to use these new files
- I transferred all the files on a SD card as usual, and set usbboot=1 and usbroot=1 in the installer-config.txt
- I rebooted the Raspi4 with the SD inserted and the SSD connected to USB, and launched the install process. Everything works as expected, but unfortunately the install.sh script fails, as line 776 checks if the device can boot from USB using the command "vcgencmd otp_dump", that is not supported on Raspi4.
- If I comment all the lines in install.sh from 776 to 790, the installer works as expected and copies both boot and root files in the SSD. 

Prior of doing that, I manually updated the EEPROM of my Raspi4 to past Aug 20 2020 version, and configured it to boot from USB using [these instructions](https://www.raspberrypi.org/documentation/hardware/raspberrypi/bootmodes/msd.md) (installed Raspberry Pi OS 2020-08-20 or newer, performed a apt full-upgrade, run rpi-config and selected _SD/USB (default)_ as boot mode), to be sure to have USB boot enabled and working.

**Comment by FooDeas** [comment]
Can you help by checking an upcoming release candidate?
