### ISSUE TITLE
Enable I2C

### ISSUE THREAD

**Issue by thijstriemstra** [FooDeas/raspberrypi-ua-netinst#22]
I want to experiment with an OLED screen using the [SSD1306 library](https://github.com/rm-hull/ssd1306) which requires I2C. Can an option be added for this (instructions [here](https://github.com/rm-hull/ssd1306#pre-requisites))?

**Comment by FooDeas** [comment]
See #21.

**Comment by thijstriemstra** [comment]
@FooDeas thanks for adding a i2c [option](https://github.com/FooDeas/raspberrypi-ua-netinst/blob/master/doc/INSTALL_CUSTOM.md#device--peripheral). After reboot I see `i2c_bm2708` enabled:

```
$ lsmod | grep i2c
i2c_bcm2708             4834  0
```

But the acual devices in /dev/ are not created. After some searching it seems i2c_dev also needs to be enabled. To accomplish this I had to add the following lines (not sure if i2c-bm2708 is also needed there), compared to an otherwise empty file apart from the comments, to `/etc/modules`:

```
# /etc/modules: kernel modules to load at boot time.
#
# This file contains the names of kernel modules that should be loaded
# at boot time, one per line. Lines beginning with "#" are ignored.

i2c-dev
i2c-bm2708
```

After reboot the devices are available:

```
$ lsmod | grep i2c
i2c_bcm2708             4834  0 
i2c_dev                 5859  0
```

```
$ sudo i2cdetect -l
i2c-1   i2c         3f804000.i2c                        I2C adapter
```

Is there something we can do about this? Shouldn't the dev devices always be available?

ps. apparently I should also change this option to increase performance (for [this device](https://github.com/rm-hull/ssd1306#pre-requisites)):

```
dtparam=i2c_arm=on,i2c_baudrate=400000
```

**Comment by FooDeas** [comment]
👍
Please put this in a new issue. Thanks!

**Comment by thijstriemstra** [comment]
Opened #43
