### ISSUE TITLE
Selecting a specific version of kernel

### ISSUE THREAD

**Issue by PUsmanKhan** [FooDeas/raspberrypi-ua-netinst#223]
I am noticing that this script installs the latest stable release of the kernel. Right now, it is 5.10.52. Can you add the feature for specifying a kernel version as some custom drivers don't work on other versions of the kernel. I once made the drivers compatible for 5.10.17 but now the kernel version is updated to 5.10.52 and this would be updating constantly in the future too, so it would be really great to specify a kernel version in the build.sh script or in the installer-config.txt file.

**Comment by FooDeas** [comment]
That is not possible because the repositories are not made for this.
