### ISSUE TITLE
Configuration to disable root

### ISSUE THREAD

**Issue by busmei** [FooDeas/raspberrypi-ua-netinst#230]
Hi,

first of all many thanks for working on this project. I really appreciate your effort and dedication.

I was playing around with the config parameters in installer-config.txt. If understood the documentation correctly, it shall be possible to disable the root account by settings rootpw as well as root_ssh_pubkey empty. So this is what I set:

username=pi
userpw=test
userperms_admin=1
rootpw=
root_ssh_pubkey=
root_ssh_pwlogin=0

However, after completing the installation I was still able to login with root/raspbian. Please correct me if my understanding is wrong. Otherwise there may be a bug somewhere.

In the meantime I use a workaround with post-install.txt containing
sed -E "s/^([root:]+:)([^:]+)(..+)$/\1!\3/g" -i /rootfs/etc/shadow

Looking forward to your feedback.

Thanks again.

BR, Mike

**Comment by TwinUsers** [comment]
Hi,

Take a look at scripts/opt/raspberrypi-ua-netinst/install.sh on line 155

variable_set "rootpw" "raspbian"

maybe this needs to be blank, so therefore you can't login

**Comment by FooDeas** [comment]
@busmei Do you mean local or SSH login?

**Comment by busmei** [comment]
@FooDeas local... Both actually. That's my intention. But I tested local only.

**Comment by FooDeas** [comment]
Disabling the SSH login should work as expected with your settings. There is no config variable to disable the local root login.
`chroot /rootfs passwd -l root` in your `post-install.txt` should also work or leave it as you already do with sed. It's the right way to do it.
