### ISSUE TITLE
Cannot install over WiFi dongle

### ISSUE THREAD

**Issue by Jodes81** [FooDeas/raspberrypi-ua-netinst#27]
The installation hangs on "Configuring eth0 with DHCP" - I've tried a couple of WiFi dongles, same problem each time.

I also tried installing via wired Ethernet which worked, and then getting WiFi to work, but often it failed to get a lease, and when it managed, it was unable to ping anything. What could be going on here?

**Comment by Jodes81** [comment]
I just re-read the readme. Sounds like the installer can only be run over WiFi if the Pi itself has built-in WiFi - so it won't work on the older Pi's with a dongle

**Comment by FooDeas** [comment]
It can work if your dongle is supported. First: the devicename has to be wlan0. Try it and report. You should check dmesg if it doesn't work! So we can find out what's missing for your dongle.

**Comment by Jodes81** [comment]
@FooDeas thank you for the quick response! I'd love for UA-NetInst to work, very powerful. 

First: I'll say that I did a sanity check - I got WiFi working successfully with the default Raspbian installed by NOOBS, by following [this tutorial](https://www.raspberrypi.org/documentation/configuration/wireless/wireless-cli.md). So in theory it should work.

Second: Trying to get the raspberrypi-ua-netinst to install over WiFi, I used the default install files, with the following modifications:

_**installer-config.txt:**_

```
packages=nano
rootsize=+3800M
cmdline="dwc_otg.lpm_enable=0 console=serial0,115200 elevator=deadline fsck.repair=yes"
wlan_ssid=TheRoutersSSID
wlan_psk=TheRoutersPassword
```

Using the UART and a serial cable to my PC, I logged the following during the install, with the network cable unplugged, and just the WiFi dongle inserted. The output to the console is this:

[install-console-log_1.txt](https://github.com/FooDeas/raspberrypi-ua-netinst/files/491304/install-console-log_1.txt)

At which point it just hangs.

Then if I plug in the network cable as well, and remove and restore power to the Pi, I get this at the console when installing:

[install-console-log_2.txt](https://github.com/FooDeas/raspberrypi-ua-netinst/files/491306/install-console-log_2.txt)

Then I log in, and see what the install gives me from the get-go:

**_ifconfig -a_**

```
eth0      Link encap:Ethernet  HWaddr b8:27:eb:25:03:8e
          inet addr:192.168.1.11  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::ba27:ebff:fe25:38e/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:638 errors:0 dropped:0 overruns:0 frame:0
          TX packets:127 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:41180 (40.2 KiB)  TX bytes:11350 (11.0 KiB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:8 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:1104 (1.0 KiB)  TX bytes:1104 (1.0 KiB)

wlan0     Link encap:Ethernet  HWaddr 00:0f:13:24:03:94
          BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```

So I run **_shutdown now_**, unplug the wired ethernet,  and boot up again:

**_ifconfig -a_**

```
eth0      Link encap:Ethernet  HWaddr b8:27:eb:25:03:8e
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

wlan0     Link encap:Ethernet  HWaddr 00:0f:13:24:03:94
          BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```

When I run **_dmesg_** I get this:

[dmesg-output.txt](https://github.com/FooDeas/raspberrypi-ua-netinst/files/491308/dmesg-output.txt)

Third: I try to get WiFi working after install. When I got WiFi working on the Raspbian distro via NOOBS, I copied **_/etc/networks/interfaces_** and **_/etc/wpa_supplicant/wpa_supplicant.conf_** to transfer them to the fresh install of raspberrypi-ua-netinst.

First I add this line to _**/etc/apt/sources.list**_:
`deb http://archive.raspbian.org/raspbian jessie main contrib non-free`

Then I run:

```
apt-get install usbutils -y
apt-get install wpasupplicant -y
apt-get install wireless-tools -y
```

And when I copy back the **_/etc/networks/interfaces_** and **_/etc/wpa_supplicant/wpa_supplicant.conf_**, and run _**ifup wlan0**_, it silently completes.

But still, when I run  **_ifconfig -a_**, it still hasn't connected:

```
eth0      Link encap:Ethernet  HWaddr b8:27:eb:25:03:8e
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

wlan0     Link encap:Ethernet  HWaddr 00:0f:13:24:03:94
          BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

```

**Comment by FooDeas** [comment]
Please post the /etc/networks/interfaces you used at the last step.

**Comment by Jodes81** [comment]
**_/etc/networks/interfaces_**

```
# interfaces(5) file used by ifup(8) and ifdown(8)
# Please note that this file is written to be used with dhcpcd
# For static IP, consult /etc/dhcpcd.conf and 'man dhcpcd.conf'
# Include files from /etc/network/interfaces.d:
source-directory /etc/network/interfaces.d
auto lo
iface lo inet loopback
iface eth0 inet manual
allow-hotplug wlan0

iface wlan0 inet manual
    wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf

allow-hotplug wlan1
iface wlan1 inet manual
    wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf
```

**_/etc/wpa_supplicant/wpa_supplicant.conf_**:

```
country=GB
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
network={
    ssid=TheSSID
    psk=ThePassword
}
```

**Comment by FooDeas** [comment]
## WiFi Setup in your fresh installed system

Your `/etc/network/interfaces`:

```
# interfaces(5) file used by ifup(8) and ifdown(8)
# Please note that this file is written to be used with dhcpcd
# For static IP, consult /etc/dhcpcd.conf and 'man dhcpcd.conf'
# Include files from /etc/network/interfaces.d:
source-directory /etc/network/interfaces.d
auto lo
iface lo inet loopback

allow-hotplug eth0
iface eth0 inet dhcp

allow-hotplug wlan0
iface wlan0 inet dhcp
    wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf
```

Your `/etc/wpa_supplicant/wpa_supplicant.conf`:

```
country=GB
network={
    ssid=<yourSSID>
    psk=<yourPass>
}
```
- You can skip modifying `/etc/apt/sources.list`. Everything needed is already included except the packages `wpasupplicant` and `firmware-realtek`.

## Now lets have a look at the installation procedure
- The installer-config.txt has to include these **four** lines:

```
...
firmware_packages=1
ifname=wlan0
wlan_ssid=<yourSSID>
wlan_psk=<yourPass>
...
```
- Try again with the missing line and I can see, what's missing when you check console output or dmesg if possible. (Firmware? Modules?)

**Comment by Jodes81** [comment]
It all works! Thank you so much!!

**Comment by FooDeas** [comment]
I don't believe the installer works using a wifi dongle (it was never intended). Using the integrated wifi of model 3 is a unique feature.
But of course, the installed system does without any problems. Glad I could help you.

**Comment by Jodes81** [comment]
Well, it worked for my dongle :) I honestly recommend this installer to anyone - it's something the RPi really needed

**Comment by FooDeas** [comment]
Okay... 😮
Nice to hear. Thanks for report!
