### ISSUE TITLE
Ethernet boot

### ISSUE THREAD

**Issue by thijstriemstra** [FooDeas/raspberrypi-ua-netinst#28]
Apparently it's possible to boot using ethernet, skipping the fragile SD-card: https://www.raspberrypi.org/blog/pi-3-booting-part-ii-ethernet-all-the-awesome/

Would love to use this with a RaspberryPi 3.

**Comment by FooDeas** [comment]
It depends on #5. Queued.

**Comment by kpfleming** [comment]
I use netbooting on most of my Pis, but I don't think it would be practical to implement support for this in the installer (I tried). Doing so requires being able to mount the target root and /boot filesystems using NFS in the installer itself, which would increase complexity significantly.

I'm satisfied using an SD card to run the installer and get a working system, then convert that system to netboot/NFS manually after the installation is complete.

**Comment by jbragdon1** [comment]
Looking over the code base, and with an admittedly limited understanding of whats going on under the hood, it looks like early on assumptions are made that there is a local file system. Once the base systems are loaded into ram - I suspect up front, checking for SD card and then writting a temp directory with tools might get this going nicely..... I would love to see this as an option linkted with a local proxy copy of the raspian installer. Effectively, plug in a pi and get it going.
