### ISSUE TITLE
Additional (new) installer-config variables for camera

### ISSUE THREAD

**Issue by Phiber2000** [FooDeas/raspberrypi-ua-netinst#3]
Should `gpu_mem` be available in `installer-config.txt`?
Other variables: `disable_camera_led` and `start_x`

@thijstriemstra
The variable `start_x` is not listed in https://www.raspberrypi.org/documentation/configuration/config-txt.md - here in http://elinux.org/RPiconfig it is. Could you check if it's still needed?

**Comment by thijstriemstra** [comment]
Yea good question. Turned out my first camera (or cable) was broken but by the time I figured that out I already configured start_x and left it as is and continued with my second camera that worked. I'll test without `start_x` and get back to you (as soon as current installer finished ;)).

**Comment by thijstriemstra** [comment]
@Phiber2000 just tested and camera didn't work without `start_x`.

**Comment by Phiber2000** [comment]
Thanks a lot for testing! It will be comfortably implemented soon!

**Comment by Phiber2000** [comment]
Done with commit 85aeebe055f8dfba975ca05a35a65ea9ba102884 and 3f7b0b27ac0caa66321e532d82e53b39829fb61d.

New release follows in a few minutes. It would be nice, if you could test the camera option!

**Comment by thijstriemstra** [comment]
Works great, thanks
