### ISSUE TITLE
Missing newline in config

### ISSUE THREAD

**Issue by thijstriemstra** [FooDeas/raspberrypi-ua-netinst#30]
I have an installer config with some gpu_mem stuff and a custom /boot/config.txt containg:

```
# Enable optional hardware interfaces
dtparam=i2c_arm=on
dtparam=i2s=on
dtparam=spi=on
```

After installation completed `/boot/config.txt` looked like this:

```
# Enable optional hardware interfaces
dtparam=i2c_arm=on
dtparam=i2s=on
dtparam=spi=onstart_x=1
disable_camera_led=1

gpu_mem=512
```

Looks like a newline was missing from my config.txt and when the final config.txt was produced it didn't add a newline, causing the dtparam option to get garbled: `dtparam=spi=onstart_x=1`

**Comment by FooDeas** [comment]
Included in v1.4.0 in last minute.

**Comment by thijstriemstra** [comment]
Still seeing the issue, refs #36

**Comment by thijstriemstra** [comment]
Confirmed it's fixed.
