### ISSUE TITLE
Build process for making raspberrypi-ua-netinst from source

### ISSUE THREAD

**Issue by Jodes81** [FooDeas/raspberrypi-ua-netinst#32]
I was wondering what the entire build process is, starting right from the source code, all the way to the released `img.*` and `.zip` files? It would be useful, so I can contribute and test? And also so I could make my own modifications? I was also thinking of forking it to make a version that is specifically oriented towards NodeJS and GPIO functionality with WiringPi in C.

**Comment by FooDeas** [comment]
Build instructions can be found in BUILD.md.
There you find the corresponding script names.
