### ISSUE TITLE
Poll: f2fs as new default filesystem

### ISSUE THREAD

**Issue by FooDeas** [FooDeas/raspberrypi-ua-netinst#34]
I'm thinking about setting [F2FS](https://en.wikipedia.org/wiki/F2FS) instead [ext4](https://en.wikipedia.org/wiki/Ext4) as a default file system.
Of course it can still be overwritten by installer-config variable.

What do you think?

**Comment by thijstriemstra** [comment]
Sounds good to me, as long as it's behind a config var. Does it require a lot of refactoring?

**Comment by FooDeas** [comment]
Only the default value of `rootfstype` would be changed for that.

**Comment by thijstriemstra** [comment]
Tested it just now and looks good so far.

**Comment by FooDeas** [comment]
...should be give more performance in some disciplines and spare flash media more than other file systems.
