### ISSUE TITLE
Shared config

### ISSUE THREAD

**Issue by thijstriemstra** [FooDeas/raspberrypi-ua-netinst#40]
I have two apps running on different raspberrypi's. I have a good config file for the first app and I would like to re-use that config file, not copy all of it's values and duplicate them in a second file. The only difference between config 1 and 2 would be the values for the `boot_volume_label`, `hostname`, 
`username`, `userpw` and `user_ssh_pubkey`.

Any suggestions how to accomplish this?

**Comment by FooDeas** [comment]
In "installer-config.txt":
- first line has to be: `sanitize_inputfile /bootfs/installer-config_common.txt`
- second line has to be: `source /bootfs/installer-config_common.txt`
- put in all **individual** options

Now create the new file "installer-config_common.txt". This is your shared file.
- put in all **common** options

This should work for you.

**Comment by thijstriemstra** [comment]
Thanks! I'll give it a try. Would be cool to have it in the documentation.

**Comment by thijstriemstra** [comment]
Will this also work with relative paths? I have app/shared/common.txt, app/app1/config.txt, and app/app2/config.txt. Guess I'll find out soon.

**Comment by FooDeas** [comment]
Good point!
You have to use the full path. I fixed my post above.
Both files should be placed in the root folder. (The installer uses `/bootfs/` for root.)

**Comment by FooDeas** [comment]
Adapted to your situation, you could use the following content of "installer-config.txt":

```
# Sanitize for compatibility
sanitize_inputfile /bootfs/app/shared/common.txt
sanitize_inputfile /bootfs/app/app1/config.txt

# Read common options
source /bootfs/app/shared/common.txt
# Read options for app1
source /bootfs/app/app1/config.txt
```

**Comment by FooDeas** [comment]
PS.: I'd rename the txt files and use "installer_config.txt". Using "config.txt" is confusing because of its ambiguity - at least for me.

**Comment by thijstriemstra** [comment]
Thanks that worked. ps. i used `config.txt` just in the example above, I've already named them how you suggested.

**Comment by thijstriemstra** [comment]
@FooDeas you suggested to use:

```
sanitize_inputfile /bootfs/installer-config-common.txt
source /bootfs/installer-config-common.txt
```

in the non-common config files. It looks like this has changed in the devel branch. Can you tell me what I should use instead for a shared config?

**Comment by FooDeas** [comment]
The "installer-config.txt" has to be placed now in `/raspberrypi-ua-netinst/config` of the sd card boot partition.

To understand: The "/bootfs/" from above represents the root of the sd card boot partition.

If you place "installer-config-common.txt" in the root folder, the path remains "/bootfs/installer-config-common.txt".
If it is placed in a subfolder "app", it's "/bootfs/app/installer-config-common.txt", etc.
