### ISSUE TITLE
install.sh has syntax error

### ISSUE THREAD

**Issue by thijstriemstra** [FooDeas/raspberrypi-ua-netinst#45]
line 409: unexpected token `fi' (using latest master)

**Comment by thijstriemstra** [comment]
@FooDeas is it possible to setup some Travis task that checks for these kind of errors? Syntax errors should never be committed.

**Comment by thijstriemstra** [comment]
@FooDeas something like https://github.com/koalaman/shellcheck

**Comment by FooDeas** [comment]
Bad day - I just forgot that. Sorry!

**Comment by FooDeas** [comment]
I added Code Climate to README.md. It will warn, if something like this happens to me again.
Thanks for the trigger!

**Comment by thijstriemstra** [comment]
Awesome, that'll safe us a lot of time :)
