### ISSUE TITLE
Move to src dir

### ISSUE THREAD

**Issue by thijstriemstra** [FooDeas/raspberrypi-ua-netinst#46]
I'd suggest to move everything related to the installer (scripts etc) to a `src` directory, so you'll end up with a repository root containing a `src` and `doc` directory.

**Comment by FooDeas** [comment]
Sounds good!

**Comment by FooDeas** [comment]
I thought about it again and looked at other Linux build projects.
Raspberrypi-ua-netinst is very similar to them and I would like to keep that.

What's different: "semi temporary" files/folders are placed in a "build_dir". ~~This only affects the folder "bootfs" but that's overwritten anyway at each build process. So I'll let it delete after build.~~
I'll adapt it.

**Comment by FooDeas** [comment]
Done with 3cf1d263eb7a614114f78b775113c14a641e8653.
