### ISSUE TITLE
Screen/HDMI option

### ISSUE THREAD

**Issue by thijstriemstra** [FooDeas/raspberrypi-ua-netinst#48]
My screen requires a different HDMI resolution with the following boot settings:

```
# uncomment to force a specific HDMI mode (this will force VGA)
hdmi_group=2
hdmi_mode=35
```

Something we want to add to the settings? A HDMI or screen section maybe?

**Comment by FooDeas** [comment]
Adding customization variables is useless for the installer itself.
It would be helpful for the system only. To get this done, you can already add these lines in `config/boot/config.txt`.

Do you want to have the installers `config.txt` this while building? Then I'm looking forward for suggestions how you'd like to customize the build process in this way - from users/your point of view. It would be a nice improvement!

**Comment by thijstriemstra** [comment]
Is there a sort of master template of all the config options available (provided by raspbian or something)? Perhaps even commented out? If we can extract all options we can decided what user-supplied values are actually valid (and should be included in /boot/config.txt).

**Comment by FooDeas** [comment]
Execute `update.sh` and have a look at `res/initramfs/boot/config.txt`. That's the **default from Raspbian** and the one that will be used, if no custom config.txt is placed in `config/boot/`.

Other/more parameters can be found in the docs [here](https://www.raspberrypi.org/documentation/configuration/config-txt.md).

**Comment by FooDeas** [comment]
But there are many more not listed on this page or "hidden" in forum threads.

**Comment by thijstriemstra** [comment]
Yea that's the problem :( I suppose this document is the most complete when it comes to  options but it's not parse-able.. https://www.raspberrypi.org/documentation/configuration/config-txt.md

**Comment by thijstriemstra** [comment]
Well in that case, why not write anything I add into the config? Ones not recognized by this lib of course.

**Comment by FooDeas** [comment]
For my understanding: Do we talk about the installation process' or the systems config.txt?

**Comment by thijstriemstra** [comment]
Anything I add to `installer-config.txt`, e.g. `spi_enable=1`, is interpreted and added to /boot/config.txt based on conditions you added right? What if you detect erroneous values, e.g. `hdmi_mode=35`, do you ignore it, or do you add it to the boot config?

**Comment by FooDeas** [comment]
"Erroneous" settings are non considered variables - so they will be completely ignored.

**Comment by thijstriemstra** [comment]
Well, let's add a var that will get parsed no matter what, andthat will be directed/appended to the boot config. Otherwise I'll keep bugging you for extra config options.. ;)

**Comment by FooDeas** [comment]
That functionality is already implemented... Just create a (empty) `config/boot/config.txt` and add your wishes there.
They will be included in systems `config.txt`.

**Comment by FooDeas** [comment]
Of course all other settings from installer-config.txt will be also considered/added to that `config.txt`.

**Comment by thijstriemstra** [comment]
Ah ok, than I've been to careful and should see what happen when I add these settings :) I'll have to mark them as such though, and try not to overlap with your settings that have the same or other (side-)effects.

**Comment by thijstriemstra** [comment]
Side-note: the options I'm asking for are mentioned in the file format example at the top of the page.. ;)

https://www.raspberrypi.org/documentation/configuration/config-txt.md

**Comment by FooDeas** [comment]
You haven't to be too careful: Settings by `installer-config.txt` always overwrite the corresponding settings in the base "template" you provide in `config/boot/config.txt`.

**Comment by FooDeas** [comment]
I thought about it and will add hdmi options. I hope to find a solution to get this applied during installation process, too.

**Comment by FooDeas** [comment]
Implementation done but untested. I hope, you can assist here.

The installation itself is not affected by the new options. I still have no good idea how the usability could look like...

**Comment by FooDeas** [comment]
Implementation done but untested. I hope, you can assist here.

The installation itself is not affected by the new options. I still have no good idea how the usability could look like...

**Comment by thijstriemstra** [comment]
I'll test it early next week, thanks!

**Comment by thijstriemstra** [comment]
Just tested it and I'm not able to get into the pi using ssh with following settings:

```
user_is_admin=1
root_ssh_pwlogin=0
ssh_pwlogin=0
root_ssh_pubkey="[real key here]"
```

Is it just me or can you reproduce this @FooDeas?

**Comment by FooDeas** [comment]
Interesting! I'll try it and report.

**Comment by FooDeas** [comment]
@thijstriemstra
I moved your request belonging SSH to #47.

**Comment by FooDeas** [comment]
With 28903e2bab9076103bd504cfb70271538814cb19, the HDMI options should apply to the installation process, too.
I'm looking forward for your test results. Please test it without providing a custom `config.txt`, too!

**Comment by thijstriemstra** [comment]
Looks good!

**Comment by FooDeas** [comment]
👍
Thanks!
