### ISSUE TITLE
Configuration API

### ISSUE THREAD

**Issue by thijstriemstra** [FooDeas/raspberrypi-ua-netinst#50]
It would be nice to define the configuration structure (keys, value types) in some sort of json object. That way it's easy for third-party (Python, JS, etc) tools to generate custom installer configuration files that can produce a custom netinst.

**Comment by FooDeas** [comment]
refs #50

**Comment by thijstriemstra** [comment]
What about adding some python unit tests that verify the config structure?

**Comment by mpmc** [comment]
The config files are already similar to ini, maybe they could be used with something like Python's [ConfigParser](https://docs.python.org/3/library/configparser.html)?

**Comment by thijstriemstra** [comment]
Think so too @mpmc

**Comment by thijstriemstra** [comment]
So I'd like to introduce some python tests that parse and verify a config file. Thoughts? Where do these tests go?
