### ISSUE TITLE
Documentation is misleading (does not match release)

### ISSUE THREAD

**Issue by bablokb** [FooDeas/raspberrypi-ua-netinst#54]
Very annoying: the documentation states that config files should go into raspberrypi-ua-netinst/config, but the installer loads (or tries to load) the installer-config.txt/post-install.txt from /bootfs (aka root of sd-card as in previous versions). This has cost me a few hours of work to figure that out.

The best way to work around this issue: keep the master in sync with the latest release and use a git branch for new developments. Or at least document which part of the documentation is valid for existing releases.

Thanks, Bernhard

**Comment by FooDeas** [comment]
Thanks for the advice!

I will implement the proposal right after the version 1.5 is released today or tomorrow.
