### ISSUE TITLE
Installer scripts may have no execution permissions

### ISSUE THREAD

**Issue by awelters** [FooDeas/raspberrypi-ua-netinst#58]
Using your code, I get passed the rainbow screen and it tells me that it can't run "/etc/init.d/rcS" because permission denied.  So what does this mean? 

With the latest version of RASPBIAN JESSIE LITE it works on my Raspberry Pi Model 2 B v1.2 (Revision a22042):

RASPBIAN JESSIE LITE
Minimal image based on Debian Jessie
Version:November 2016
Release date:2016-11-25
Kernel version:4.4

The linux kernel installed is 4.4.34-v7+

**Comment by FooDeas** [comment]
Please attach the installer log!

**Comment by awelters** [comment]
Nevermind I was able to get it to work, sorry!

**Comment by FooDeas** [comment]
Nice, but it would be good to know, what was caused the problem.
I see no potential cause for this issue on that specific model...
The kernel and SoC is identical (with lower frequency) to the model 3, which is part of my pre-release test environments. Of course with no problems...

**Comment by awelters** [comment]
Your code works just fine I should say.  What happened is related to making sure that the rcS file has the right permissions on it before you run the build script otherwise it won't be executable on the PI.  So on my build machine I ran the following:  'chmod 751 rcS'.

**Comment by FooDeas** [comment]
Weird that this never happened in my and others test cases...
Thanks! I'll have a look at it.

**Comment by FooDeas** [comment]
This can happen if the scripts in the scripts folder have no execution permission before building.
