### ISSUE TITLE
Files in `config` are not copied to installer

### ISSUE THREAD

**Issue by Mausy5043** [FooDeas/raspberrypi-ua-netinst#60]
Files that I place in the `config` tree (before starting `build.sh`) do not end up on the image for the installer.

I think that is because here: https://github.com/FooDeas/raspberrypi-ua-netinst/blob/master/build.sh#L626 you `cd` into the `build_dir` and then this: 
https://github.com/FooDeas/raspberrypi-ua-netinst/blob/master/build.sh#L671-L673 won't find anything to copy anymore.

What do you think?

**Comment by FooDeas** [comment]
I think, you were right! Thanks!
