### ISSUE TITLE
Local mirror for debian packages

### ISSUE THREAD

**Issue by thijstriemstra** [FooDeas/raspberrypi-ua-netinst#63]
I currently have limited bandwidth and would like to setup a local mirror for the required debian packages. Should changing the `mirror` setting be enough? I'll look into [apt-cacher](https://packages.debian.org/jessie/apt-cacher) ([instructions](https://help.ubuntu.com/community/Apt-Cacher-Server)) on how to get these packages in my local mirror.

**Comment by thijstriemstra** [comment]
`apt-cacher` is up and running on my host machine. Created `/etc/apt/apt.conf.d/01proxy` on the Raspberry Pi with the following (no other changes/installation needed on the client rpi, except for the `mylocal.apt` addition to `/etc/hosts`):

```
Acquire::http::Proxy "http://mylocal.apt:3142";
```

Now I'll have to figure out if the mirror setting can be replaced by the proxy url above, or if the presence of a `01proxy` file would be required as well.

**Comment by thijstriemstra** [comment]
Results are in.

Without supplying a custom `/etc/apt/apt.conf.d/01proxy` and just a mirror,

```
mirror=http://192.168.2.50:3142/mirrordirector.raspbian.org/raspbian/
```

it used the apt-cacher server for the first packages. As soon as it started to install the `minimal` or `server` package and my custom packages, it did not use the apt-cacher server.

Unfortunately I could not use `mylocal.apt` because the rpi does not know about hosts at the initial stage of the installation process, or does it? With an IP address it works fine.

Before trying to copy a `/etc/apt/apt.conf.d/01proxy` as well, do you think that would work @FooDeas?

**Comment by FooDeas** [comment]
I recommend to use [apt-cacher-ng](https://packages.debian.org/jessie/apt-cacher-ng) for this because it doesn't need a separate webserver (Apache).

I hope, this will fix your problem:
- check, if `archive.raspberrypi.org/debian` is configured/allowed by the cacher, too (this might be your problem)
- add custom ~~list~~ **conf** file ~~raspberrypi-ua-netinst/config/apt/01proxy.list~~ `raspberrypi-ua-netinst/config/apt/01proxy.conf`:
`Acquire::http::Proxy "http://<CacherIP>:3142/";`

**Comment by thijstriemstra** [comment]
- there's a  `/var/cache/apt-cacher-ng/archive.raspberrypi.org` on the cache machine so I'm sure it's being cached without any extra config
 - I'll try that, thanks for the feedback.

**Comment by thijstriemstra** [comment]
Your second suggestion resulted in this error:

```
Configuring apt:
  Configuring Raspbian repository... OK
  Checking Raspbian repository entry... OK
  Adding raspberrypi.org GPG key to apt-key... OK
  Configuring RaspberryPi repository... OK
  Configuring RaspberryPi preference... OK
  Copying './01proxy.list' to /etc/apt/sources.list.d/... OK
  Copying './foo.apt.list' to /etc/apt/sources.list.d/... OK
  Adding key './foo.gpg.key' to apt.OK
OK

Updating package lists... ERROR: 100, trying again (2/3)... ERROR: 100, trying again (3/3)... ERROR: 100, FAILED !

Oh noes, something went wrong!
You have 10 seconds to hit ENTER to get a shell...
```

I'll do a manual file copy to `/etc/apt/apt.conf.d/01proxy` now.

**Comment by FooDeas** [comment]
Looks like a previous bugfix (8429bd843c17bf02de8d32f847c0c52841e29c78) causes this bug.
I'll have a look at it!

**Comment by thijstriemstra** [comment]
This didn't work either, and it's quite obvious why; copying the root files I supplied happens after downloading all packages. I'm now testing with:

```diff
diff --git a/scripts/opt/raspberrypi-ua-netinst/install.sh b/scripts/opt/raspberrypi-ua-netinst/install.sh
index 430d856..97ba936 100644
--- a/scripts/opt/raspberrypi-ua-netinst/install.sh
+++ b/scripts/opt/raspberrypi-ua-netinst/install.sh
@@ -1490,13 +1490,23 @@ done
 # iterate through all the *.pref files and add them to /etc/apt/preferences.d
 for preffile in ./*.pref
 do
-       if [ "${listfile}" != "./archive_raspberrypi_org.pref" ] && [ -e "${preffile}" ]; then
+       if [ "${preffile}" != "./archive_raspberrypi_org.pref" ] && [ -e "${preffile}" ]; then
                echo -n "  Copying '${preffile}' to /etc/apt/preferences.d/... "
                sed "s/__RELEASE__/${release}/g" "${preffile}" > "/rootfs/etc/apt/preferences.d/${preffile}" || fail
                echo "OK"
        fi
 done
 
+# iterate through all the *.conf files and add them to /etc/apt/apt.conf.d
+for conffile in ./*.conf
+do
+    if [ "${conffile}" != "./archive_raspberrypi_org.pref" ] && [ -e "${conffile}" ]; then
+        echo -n "  Copying '${conffile}' to /etc/apt/apt.conf.d/... "
+        sed "s/__RELEASE__/${release}/g" "${conffile}" > "/rootfs/etc/apt/apt.conf.d/${conffile}" || fail
+        echo "OK"
+    fi
+done
+
 # iterate through all the *.key files and add them to apt-key
 for keyfile in ./*.key
 do
```

I also think the first changed line in this diff above is a bugfix @FooDeas.

But it's probably better if I only want to persist that mirror after installation. During installation the `mirror` option should always apply, or some `mirror_cache` value that can be prepended to any repo address used during installation.

**Comment by thijstriemstra** [comment]
Well, that seems to have worked :)
```
Configuring apt:
  Configuring Raspbian repository... OK
  Checking Raspbian repository entry... OK
  Adding raspberrypi.org GPG key to apt-key... OK
  Configuring RaspberryPi repository... OK
  Configuring RaspberryPi preference... OK
  Copying './foo.apt.list' to /etc/apt/sources.list.d/... OK
  Copying './01proxy.conf' to /etc/apt/apt.conf.d/... OK
  Adding key './foo.gpg.key' to apt.OK
OK
```

**Comment by thijstriemstra** [comment]
After installation my network won't come up though, did something change in relation to that in the `dev` branch? This watchdog stuff? Because I'm also not seeing the whole system launch being logged anymore, it only shows a quick fcdisk check and then shows the prompt.

Only after a `sudo service networking restart` an IP address was assigned.

**Comment by FooDeas** [comment]
I tested the last dev build successfully before pushing it. I think your broken installation is caused by missing packages.

Where is your `foo.apt.list` and `foo.gpg.key` from? This could be the reason, that apt can't read the package list!

I setup my own default configured apt-cacher-ng and will test it.

**Comment by thijstriemstra** [comment]
Thanks for your feedback. I will go through the logs and see if there's anything related to missing packages. The foo.apt.list and key are copied to the config/apt folder before installation.

**Comment by FooDeas** [comment]
Please make a fresh clone of the repo. These files shouldn't be there.

**Comment by thijstriemstra** [comment]
No, they're copied by me in order to add a custom repository, suggested by you in some ticket months ago (and it worked fine).

**Comment by FooDeas** [comment]
I'm amazed that you didn't change the filenames...
Does the apt proxy have access to this custom repository?

**Comment by thijstriemstra** [comment]
Of course I did, but for this ticket I used `foo` buddy ;) And yes, custom repo + cacher are on the same machine.

**Comment by FooDeas** [comment]
I can confirm your problem, that updating package list when using the proxy fails.
I'm checking out why.

**Comment by FooDeas** [comment]
I can confirm your problem, that updating package list when using the proxy fails.
I'm checking out why.

**Comment by FooDeas** [comment]
I think, your patch above was pretty perfect and damn near to my solution...
I'm testing. 👍

**Comment by FooDeas** [comment]
It's working if you name the file `01proxy.conf` now.
Thanks for your enhancement suggestion!

**Comment by thijstriemstra** [comment]
ah great thanks! Also, can you merge it to master and/or make a new release?

**Comment by FooDeas** [comment]
I could - but I wanted to fix wheezy installation before. There are some weird things regarding loading kernel modules happening when the old wheezy kernel is used.
I'd invest 1-2 days for it and see, if this can be fixed. If not - I'll release this version without full featured wheezy.

**Comment by thijstriemstra** [comment]
sounds good.

**Comment by thijstriemstra** [comment]
@FooDeas there's still something wrong with the network/whole initialization of the system. When I boot the raspberrypi, after successful installation, it shows 4 lines almost instantly, doing a fsck disk scan and then I see the prompt. What I don't see is network/systemd configuration etc and I don't have network. When I manually login and restart the network it gives me a proper IP. Any idea? Or should I compare to master first? :(

**Comment by FooDeas** [comment]
I did some further testruns without problems using devel branch.
Checkout master and give it a try to ensure that this is a coding problem.

Paste problems in #64.

**Comment by FooDeas** [comment]
A HTTP apt proxy can now be specified in installer-config. The 01proxy.conf is only needed to configure the system itself to use the proxy.
The building environment now has a config file too, to specify an apt proxy.

**Comment by thijstriemstra** [comment]
Thanks @FooDeas, tested and works fine. Network issue is also gone so it must be something with my DHCP server (which is also running on a different RPI). Saw one thing in the log that is worth pointing out:

```
Configuring installed system:
mount: mounting /run on /rootfs/run failed: No such file or directory
  Setting root password... OK
  Disabling SSH password login for users... OK
```
Or can that mount error be ignored?

**Comment by FooDeas** [comment]
The unmount errors are blemish, which I will care about.
