### ISSUE TITLE
Test devel branch for new release v1.5.1

### ISSUE THREAD

**Issue by FooDeas** [FooDeas/raspberrypi-ua-netinst#64]
My tests with all new features were successful.

Please report issues here. Verify against master to check if they originate from new implementations.

Tbd:
- ~~installer: cleanup unmounts~~ ae82068458563a72523601267537f405d475d194
- ~~build: updater wget error handling/messages~~ 9e25283ce6e52fd5ae2299aef162bad99cbf0348
- ~~build: fix download protocol~~ 63ba9849d739f2051d73c0280688f1d07eeb7e87
- ~~doc: change description of mirror_cache~~ d2eb085373ea03cccd397844c93f7abbf786010a, 74619f883f361a23cc332d21f5b968e6d39047c8

**Comment by Mausy5043** [comment]
update.sh on the `devel` branch produces undesirable output:
```
pi@rbian ~/builder/raspberrypi-ua-netinst $ ./update.sh
Setting up gpg...
gpg: keyring `gnupg/secring.gpg' created
gpg: keyring `gnupg/pubring.gpg' created
gpg: gnupg/trustdb.gpg: trustdb created

Downloading raspbian.public.key.
raspbian.public.key                        100%[========================================================================================>]   1.73K  --.-KB/s   in 0s
Checking key file 'raspbian.public.key'... OK
Importing 'raspbian.public.key' into keyring... OK

Downloading raspberrypi.gpg.key.
raspberrypi.gpg.key                        100%[========================================================================================>]   1.68K  --.-KB/s   in 0.001s
Checking key file 'raspberrypi.gpg.key'... OK
Importing 'raspberrypi.gpg.key' into keyring...OK

Downloading Release file and its signature...
Verifying Release file... ERROR
Broken GPG signature on Release file!
```

EDIT: This doesn't happen with the `master` branch

**Comment by FooDeas** [comment]
@Mausy5043
Are you using a (caching) proxy?

**Comment by Mausy5043** [comment]
Not that I'm aware of

**Comment by FooDeas** [comment]
The connection to some files on the repository fails.
The error message is missleading. (And has to be improved...) ~~Maybe they are updating it at the moment. This happened often to me. Please try again in some minutes and report!~~

@Mausy5043
Bug found and fixed in 63ba9849d739f2051d73c0280688f1d07eeb7e87.
Error messages more verbose in 9e25283ce6e52fd5ae2299aef162bad99cbf0348.

**Comment by Mausy5043** [comment]
No problem building and installing with the current `devel` branch.

**Comment by FooDeas** [comment]
Last changes were minor, non critical.

@thijstriemstra: Any other potential problems?

If there is nothing else, I'd like to issue the release in about 15 hours...

**Comment by thijstriemstra** [comment]
cool, checking now...

**Comment by thijstriemstra** [comment]
+1

**Comment by FooDeas** [comment]
Thanks a lot!

It's done: [raspberrypi-ua-netinst - Release v1.5.1](https://github.com/FooDeas/raspberrypi-ua-netinst/releases/tag/v1.5.1)
