### ISSUE TITLE
Post installer script found no command

### ISSUE THREAD

**Issue by kraeml** [FooDeas/raspberrypi-ua-netinst#67]
I created a post-install.txt. After running  raspberrypi-ua-netinst I found this message:

```bash
sudo tail /var/log/raspberrypi-ua-netinst.log
=================================================
=== Start executing post-install.txt. ===
/bootfs/raspberrypi-ua-netinst/config/post-install.txt: line 2: /bin/su: No such file or directory
/bootfs/raspberrypi-ua-netinst/config/post-install.txt: line 3: /bin/su: No such file or directory
=== Finished executing post-install.txt. ===
=================================================
Removing cdebootstrap-helper-rc.d... OK
Saving current time for fake-hwclock... OK

Installation finished at Sat Apr  1 08:41:32 UTC 2017 and took 43 min 37 sec (2617 seconds)
```

The post-install.txt is:

```bash
cat -A /boot/raspberrypi-ua-netinst/config/post-install.txt
#!/bin/bash$
/bin/su -lc "/usr/bin/git clone https://kraeml@gitlab.com/kraeml/raspberry-edu-devops.git /home/pi/.raspberry-edu-devops" pi$
/bin/su -lc "cd /home/pi/.raspberry-edu-devops && ./install_jns_medium.sh" pi$
```

My installer-config.txt
```bash
cat -A /boot/raspberrypi-ua-netinst/config/installer-config.txt
packages="vim,python-minimal,apt-transport-https,debian-archive-keyring,ca-certificates,screen,tmux,git,pandoc,stow,nginx"$

$
firmware=1$
$
timezone="Europe/Berlin"$
keyboard_layout="de"$
system_default_locale="de_DE.UTF-8"$
locales="de_DE.UTF-8, en_US.UTF-8"$
$
username="pi"$
userpw="SECRET"$
user_is_admin=1$
$
usergpu=1$
usergpio=1$
i2c_enable=1$
spi_enable=1$
sound_enable=1$
camera_enable=1$
$
root_ssh_allow=0$
rootpw=""$
root_ssh_pwlogin=0$
$
hostname="pi3-xy"$
$
wlan_country="DE"$
wlan_ssid="_removed_"$
wlan_psk="_removed_"$
$
usbroot=1$
rootfstype="ext4"$
$
enable_watchdog=1$
$
gpu_mem=16$
hdmi_system_only=1$
```

After the reboot I found su with:

```bash
which su
/bin/su
```

The script `sudo /boot/raspberrypi-ua-netinst/config/post-install.txt` runs.

Any suggestions?

Thanks for this cool repro

kraeml

**Comment by FooDeas** [comment]
The post install script runs in installer context.
So you have to chroot to do the commands in the installed system: `chroot /rootfs`
If you execute this as separate command, don't forget the `exit` as last command in your post-install script.

**Comment by kraeml** [comment]
Thanks, I never used chroot before. 

I changed my post-install.txt into:

```bash
cat -A /boot/raspberrypi-ua-netinst/config/post-install.txt                                                                                                                                                                                                       
#!/bin/bash$                                                                                                                                                                                                                                                                   
chroot /rootfs /bin/bash -c '/bin/su -lc "/usr/bin/git clone https://kraeml@gitlab.com/kraeml/raspberry-edu-devops.git /home/pi/.raspberry-edu-devops" pi'$ 
```

The log file says:

```bash
=================================================
=== Start executing post-install.txt. ===
fatal: open /dev/null or dup failed: Permission denied
=== Finished executing post-install.txt. ===
=================================================
```

I now try do mount this before chroot:

```bash
mount -t proc proc /rootfs/proc/
mount -t sysfs sys /rootfs/sys/
mount -o bind /dev /rootfs/dev/
```
Now the log is:

```bash
=================================================
=== Start executing post-install.txt. ===
mount: mounting proc on /rootfs/proc/ failed: Device or resource busy
mount: mounting sys on /rootfs/sys/ failed: Device or resource busy
fatal: open /dev/null or dup failed: Permission denied
=== Finished executing post-install.txt. ===
=================================================
```
May you have suggestions?

kraeml

**Comment by Mausy5043** [comment]
In the `post-install.txt` there is no need to `su` or start a new shell. You already have root permissions.  

Try it like this:
```
chroot /rootfs /usr/bin/git clone https://kraeml@gitlab.com/kraeml/raspberry-edu-devops.git /home/pi/.raspberry-edu-devops
chroot /rootfs cd /home/pi/.raspberry-edu-devops && ./install_jns_medium.sh
```

then take it from there.  
The script will think it is running inside the installed system with the installer's kernel and with root-priveledges. The script won't like that because of this piece of code at the start of it:
```
if [ $(id -u) = 0 ]; then
   echo "to be run without sudo"
   exit 1
fi
```

PS: the $-signs in your quotes are really confusing. Please don't do that.

**Comment by FooDeas** [comment]
I think @Mausy5043's suggestion will solve your problem.

**Here is another useful hint for debugging purposes:**
Add `final_action=console` to your installer-config.txt. After installing, the installer will now end in console mode (default is to reboot)! There you can test your commands, which you would like to add to the post-install.txt. If they succeed in this mode, they will succeed in the script, too.

This way, you won't loose as much time as you would loose by running the installer again and again...

**Comment by kraeml** [comment]
@Mausy5043 Thanks. The line 

```bash
chroot /rootfs /usr/bin/git clone https://kraeml@gitlab.com/kraeml/raspberry-edu-devops.git /home/pi/.raspberry-edu-devops
```
works.

I use su to switch user to _pi_. The script should not run as root. 

My solution now is your repro [raspboot](https://github.com/Mausy5043/raspboot) thanks for that. It works fine - not the origin script but the idea with cronjob and firstboot ...

This works now the next houres to install my project.

With cat -A I could show that the spaces are ASCII-Spaces not UTF-8 double byte characters. Sorry for confusing.

@FooDeas thanks for this. My script is running (~6h). I will test it next time.

**Comment by thijstriemstra** [comment]
Can this be closed @kraeml?

**Comment by kraeml** [comment]
Yes I close this issue. Thanks for your help.
