### ISSUE TITLE
APT error

### ISSUE THREAD

**Issue by TimVNL** [FooDeas/raspberrypi-ua-netinst#68]
Hi,

I have an issue with the installer when I add custom apt sources with (public) GPG keys 

I get the following error:

onfiguring apt:
  Configuring Raspbian repository... OK
  Checking Raspbian repository entry... OK
  Adding raspberrypi.org GPG key to apt-key... OK
  Configuring RaspberryPi repository... OK
  Configuring RaspberryPi preference... OK
  Copying './jessie-backports.list' to /etc/apt/sources.list.d/... OK
  Copying './sury-php.list' to /etc/apt/sources.list.d/... OK
  Copying './debian-archive-jessie.gpg' to /etc/apt/trusted.gpg.d/... OK
  Copying './debian-archive-wheezy.gpg' to /etc/apt/trusted.gpg.d/... OK
  Copying './sury-php.gpg' to /etc/apt/trusted.gpg.d/... OK

Updating package lists... ERROR: 100, trying again (2/3)... ERROR: 100, trying again (3/3)... ERROR: 100, FAILED !

Oh noes, something went wrong!
You have 10 seconds to hit ENTER to get a shell...

Raspberry info:  
Revision v1.5.1 (bd078c1)
Built on Wed Jan 25 12:41:03 CET 2017
Running on Raspberry Pi version 3 Model B  

also it's not placing files and I have a files. list in /raspberrypi-ua-netinst/config/files/root folder it looks like:

timv:timv           755   /home/timv/.bash_prompt
timv:timv           755   /home/timv/.bashrc
www-data:www-data   755  /var/www/index.html
www-data:www-data   755  /var/www/404.html
www-data:www-data   755  /var/www/503.html

**Comment by TimVNL** [comment]
Found the error with apt it missing  

apt-transport-https  

it is needed even tho I am using http URLS, maybe add this before apt sources etc... are added.

**Comment by FooDeas** [comment]
The list file has to be innthe same folder as the sample file. Is it?

**Comment by FooDeas** [comment]
Thanks for the apt info! It will be fixed very soon.

**Comment by FooDeas** [comment]
@TimVNL
- Not installing files issue:
The **custom files** list file has to be in the same folder as the sample file (custom_files.txt). Only the source files have to be in the subfolder `root`. Is it?
- Missing apt-transport-https issue:
I'd be happy, if you could test ~~8f08a9a~~ ~~8fe53df5d95a480b9f3e81d41f518e079965ffbe~~ 0c186445aee2782214a114ba4963ce6afdfa9a34. It should be fixed there.

**Comment by TimVNL** [comment]
@FooDeas 

* Fixed the custom files issue wasn't paying attention.
* Will test this as soon as I have me new rpi ;)
  
Also maybe make a guide for exporting keys to put in the apt folder.
