### ISSUE TITLE
find error in install.sh

### ISSUE THREAD

**Issue by Mausy5043** [FooDeas/raspberrypi-ua-netinst#69]
[Line 715 in install.sh](https://github.com/FooDeas/raspberrypi-ua-netinst/blob/devel/scripts/opt/raspberrypi-ua-netinst/install.sh#L715) results in this partial log output during installing:

```
:
Set time using ntpdate... OK

Installation started at Sat Apr 22 10:04:55 UTC 2017 (UTC).

find: /rootfs/boot/raspberrypi-ua-netinst/config/apt/: No such file or directory

Installer configuration:
  preset = server
:
```

No problem for script continuity.

**Comment by FooDeas** [comment]
Thanks. It's a cosmetic issue that came with #68.
It doesn't have functional impact, but I'll improve this today!
