### ISSUE TITLE
Add user to groups

### ISSUE THREAD

**Issue by thijstriemstra** [FooDeas/raspberrypi-ua-netinst#7]
I have an install.sh on the pi that adds the user to several groups, e.g.:

```
# setup permissions: add user to video, lpadmin, input and gpio groups
echo "Creating permissions..."
sudo groupadd -f -r gpio
sudo usermod -a -G gpio,lpadmin,video,input $(whoami)
```

Would be nice to have a setting that adds you to specified groups (and creates the group if it doesn't exist).

**Comment by FooDeas** [comment]
Good idea!
