### ISSUE TITLE
Limit install retries

### ISSUE THREAD

**Issue by dinosore** [FooDeas/raspberrypi-ua-netinst#72]
This is based on git-6e67710 on a pi 0w..
zip of relevant files attached.

note final_action=halt and a full stop rather than a comma before ntfs-3g.

On finding the error, I expected the processor to halt and the activity light to go out.

I left it going for a few hours.  It looks like, rather than halting, it rebooted and tried again.  See the multiple error loga.
[
[raspberrypi-ua-netinst.zip](https://github.com/FooDeas/raspberrypi-ua-netinst/files/965776/raspberrypi-ua-netinst.zip)
](url)

**Comment by FooDeas** [comment]
Only your packages setting in the config is wrong (line 16). I'd recommend using one singe line, too.
"final_action" is the final action when **finished**. In case of errors it reboots and retries as intended.

**Comment by dinosore** [comment]
You have every right to consider this a feature, working as designed.

I would call it an infinite loop. :-) 

 A limit would be good, but probably not important enough to implement.

**Comment by FooDeas** [comment]
Thanks for suggestion!

**Comment by FooDeas** [comment]
Done in 83adf4278abe51ac631fbcb6294756f9eee96c58.
