### ISSUE TITLE
Check RTC access before installation starts

### ISSUE THREAD

**Issue by thijstriemstra** [FooDeas/raspberrypi-ua-netinst#74]
I have the rtc option enabled:

```
rtc=ds3231
```

but forgot to hook up the actual rtc device before installation. After everything installed the process died with:

```
=== Finished executing post-install.txt. ===
=================================================
Removing cdebootstrap-helper-rc.d... OK
Saving current time to RTC... hwclock: can't open '/dev/misc/rtc': No such file or directory

Oh noes, something went wrong!
You have 10 seconds to hit ENTER to get a shell...
```

But after that it rebooted, but I only saw a blank screen with a blinking cursor. After waiting a few mins I decided to take out the sd-card and check the error log where I found this error.

I then hooked up the rtc device and powered up the rpi again. I expected the process to either restart or continue where it left of but instead nothing happened, and there was no new error in the logs either.

So I wiped the card and started from scratch, this time making sure the rtc device was hooked up, waiting to see if it works now.

Is it possible to either ignore this error, or properly reboot and try again (until it's properly hooked up)?

**Comment by thijstriemstra** [comment]
Perhaps this step can also be executed earlier?

**Comment by thijstriemstra** [comment]
Tried again and getting the same error. Only this time it took me into an emergency console after a timeout for mmcblk0p1.device..

**Comment by thijstriemstra** [comment]
Seeing this error as well:

```
  Failed to set capabilities on file `/usr/bin/systemd-detect-virt' (Invalid argument)
  The value of the capability argument is not permitted for a file. Or the file is not a regular (non-symlink) file
  Adjusting cmdline.txt...
  Removing old sysctl tweaks, if present...
  Removing old NOPASSWD line, if present...
  sed: can't read /etc/sudoers: No such file or directory
  Failed
  Updating documentation URL in /boot/config.txt...
  Setting up pi-bluetooth (0.1.3) ...
```

Update: the `sed: can't read /etc/sudoers: No such file or directory` is related to me using a deprecated parameter, the other one is not.

**Comment by thijstriemstra** [comment]
More errors:
```
Configuring installed system:
mount: mounting /run on /rootfs/run failed: No such file or directory
  Setting root password... OK
  Disabling SSH password login for users... OK
```

```
  P: Configuring package raspbian-archive-keyring
  P: Configuring package apt
  P: Configuring helper cdebootstrap-helper-apt
  E
  : 
  Can not write log (Is /dev/pts mounted?) - posix_openpt (19: No such device)
  P: Unpacking package init-system-helpers
  P: Unpacking package cron
  P: Unpacking package groff-base
```

**Comment by thijstriemstra** [comment]
I also see this twice (note the weird path `/boot/raspberrypi-ua-netinst/config/files/./installation-files.list`):

```
Adding files & folders listed in /boot/raspberrypi-ua-netinst/config/files/./installation-files.list...
  /etc/udev/rules.d/99-escpos.rules
  /etc/lsyncd.conf
  /etc/hosts
  /etc/asound.conf

=================================================
=== Start executing post-install.txt. ===
Adding files & folders listed in /boot/raspberrypi-ua-netinst/config/files/installation-files.list...
  /etc/udev/rules.d/99-escpos.rules
  /etc/lsyncd.conf
  /etc/hosts
  /etc/asound.conf

=== Finished executing post-install.txt. ===
=================================================
```

**Comment by thijstriemstra** [comment]
Looks like some of the errors we're caused by using a deprecated parameter, switching to `userperms_admin=1` now. But then the fallback mechanism you created for deprecated params isn't functioning correctly.

**Comment by FooDeas** [comment]
1. Please check your `post-install.txt`. I don't know what's going on there.
1. The deprecated code should work as expected.
1. "Can not write log..." error occurs many times but in 9 of 10 it gets filtered. You can safely ignore these.
1. "can't read /etc/sudoers..." is totally weired.

Could you please attach/send a full log??

**Comment by thijstriemstra** [comment]
> "can't read /etc/sudoers..." is totally weired.

It's because sudo wasn't installed at all (because I was using an old var)

**Comment by FooDeas** [comment]
I tested the deprecated code. The old var shouldn't have impact here...

**Comment by FooDeas** [comment]
Bug found.

**Comment by thijstriemstra** [comment]
@FooDeas what bug(s) exactly?

**Comment by FooDeas** [comment]
2. and 4. is a bug in devel.
3. has to be ignored be ignored

**Comment by FooDeas** [comment]
Notice that this bug is only present in devel! I'm testing new code with some fixes.

**Comment by FooDeas** [comment]
Please test a00f0b1c588040e6e2c9f60e398d0ed8768570eb. Feel free to use deprecated variables!

**Comment by FooDeas** [comment]
Bugfix in a6c418dcd9090444b91a170c7618300ed4f1fbe5
Done in a00f0b1c588040e6e2c9f60e398d0ed8768570eb
