### ISSUE TITLE
Use apt-cacher-ng for wget

### ISSUE THREAD

**Issue by thijstriemstra** [FooDeas/raspberrypi-ua-netinst#75]
```
nano ~/.wgetrc
```
```
# wget run control file for current user
# tell wget to use a proxy, apt-cacher-ng which listens on 3142
http_proxy = http://localhost:3142
https_proxy = http://localhost:3142
use_proxy = on
wait = 15
```

I bet there are more besides wget (curl?) so maybe the setting should be a list of programs that allow an apt-cacher like wget.

**Comment by thijstriemstra** [comment]
Unfortunately that doesn't seem to work on HTTPS (and couldn't get it to work with http either):

```
$ wget https://www.usconstitution.net/const.txt
--2017-05-06 18:11:22--  https://www.usconstitution.net/const.txt
Resolving mylocalserver.apt (mylocalserver.apt)... 192.168.2.50
Connecting to mylocalserver.apt (mylocalserver.apt)|192.168.2.50|:3142... connected.
Proxy tunneling failed: CONNECT denied (ask the admin to allow HTTPS tunnels)Unable to establish SSL connection.
```

**Comment by thijstriemstra** [comment]
Haven't been able to get this to work and not convinced it even can work so closing this.

**Comment by FooDeas** [comment]
I don't think, https is very important for (mostly) local apt cachers. But when I've got time, I'd have a closer look on this.

**Comment by FooDeas** [comment]
Apt-cacher is designed for use with apt only.
