### ISSUE TITLE
Enable additional (audio) dtoverlays

### ISSUE THREAD

**Issue by thijstriemstra** [FooDeas/raspberrypi-ua-netinst#78]
I need to add `dtoverlay=hifiberry-dac`. Can we create a setting for this?

Also see https://learn.adafruit.com/adafruit-max98357-i2s-class-d-mono-amp?view=all#add-device-tree-overlay

**Comment by FooDeas** [comment]
I'm thinking about a more general solution to enable custom overlays. Hifiberry alone has already four different values...
What do you think about this?

**Comment by thijstriemstra** [comment]
Definitely! But let's put out a new release first, we should be 'syncing dev to master' more often (last time was jan 25), e.g. put out new releases.

**Comment by FooDeas** [comment]
Please help me testing it. 👍
