### ISSUE TITLE
Control screensaver

### ISSUE THREAD

**Issue by thijstriemstra** [FooDeas/raspberrypi-ua-netinst#79]
Looks like a screensaver is enabled by default. An option to change the time, or to disable it completely, would be useful.

**Comment by FooDeas** [comment]
Good point!

**Comment by thijstriemstra** [comment]
To disable it, edit the file `/etc/kbd/config`:
```
BLANK_TIME=0
BLANK_DPMS=off
POWERDOWN_TIME=0
```

**Comment by thijstriemstra** [comment]
Hmm just enabled it 15 mins ago and console's blank again, there's more to it I guess..

**Comment by thijstriemstra** [comment]
Another source suggests: To prevent the screen from going blank try adding `consoleblank=0` to the end of the first line of `/boot/cmdline.txt`. Testing.. **works**

**Comment by FooDeas** [comment]
Forgot to doc the zero...
