### ISSUE TITLE
Testing for upcoming release

### ISSUE THREAD

**Issue by FooDeas** [FooDeas/raspberrypi-ua-netinst#81]
I'd release the v1.5.2 ~today at 18:00 UTC~ very soon. Features are fixed and can be found in the changelog text file.
If anyone discovers a bug, please post it here!

Note that the deprecated commits before july 2016 will get sqashed then, so local repositories will require a rebase.

**Comment by thijstriemstra** [comment]
Haven't had time lately (was focused on cryptocurrencies ;) but I'll try to test this asap.

**Comment by thijstriemstra** [comment]
@FooDeas I enabled the following:

```
preset=server
firmware_packages=1
packages=git,unzip,nano,libffi-dev,libi2c-dev,i2c-tools,libbz2-dev,pciutils,libsqlite3-dev,libncurses-dev,usbutils,libusb-dev,libyaml-dev,xz-utils,raspberrypi-sys-mods,bluez,bluetooth,pi-bluetooth,libbluetooth3,libbluetooth-dev,libdbus-c++-dev,libdbus-1-dev,libinput-dev,libinput5,lsyncd,samba,autofs,cifs-utils,libspeechd-dev,flite,flite-dev
usersysgroups=lpadmin,lp,dialout,input,audio,spi,i2c
userperms_admin=1
root_ssh_pwlogin=0
ssh_pwlogin=0
user_ssh_pubkey=foo.pub
timezone=Europe/Amsterdam
locales="en_US.UTF-8,nl_NL.UTF-8"
system_default_locale="en_US.UTF-8"
gpu_mem=512
spi_enable=1
i2c_enable=1
i2c_baudrate=400000
sound_enable=1
sound_usb_enable=1
sound_usb_first=1
userperms_sound=1
camera_enable=1
camera_disable_led=1
usergpio=1
usergpu=1

hdmi_monitor_res=640x480
hdmi_disable_overscan=1
console_blank=0
quiet_boot=1
disable_raspberries=1
disable_splash=1
cleanup=1
cleanup_logfiles=1
```

And something went wrong because the resulting `config.txt` contains:

```
[all]
initramfs raspberrypi-ua-netinst/raspberrypi-ua-netinst.cpio.gz
[pi3]
enable_uart=1

# Only for RPi model 3: The following line enables the ability to boot from USB.
# Notice: This flag will be written to OTP and is permanent.
#program_usb_boot_mode=1
disable_overscan=1
disable_overscan=1
disable_overscan=1
disable_overscan=1
disable_overscan=1
disable_overscan=1
disable_overscan=1
disable_overscan=1
disable_overscan=1
disable_overscan=1
disable_overscan=1
disable_overscan=1
disable_overscan=1
disable_overscan=1
disable_overscan=1
disable_overscan=1
disable_overscan=1
disable_overscan=1
disable_overscan=1
disable_overscan=1
disable_overscan=1
disable_overscan=1
```

And I couldn't find any error log..

**Comment by thijstriemstra** [comment]
any idea @FooDeas?

**Comment by FooDeas** [comment]
Yep. Just a bit busy atm.

**Comment by FooDeas** [comment]
Finally! The `disable_overscan` bug is fixed.

Fya: `hdmi_monitor_res=640x480` doesn't make sense and gets ignored if `hdmi_type` isn't set to `monitor`.

**Comment by thijstriemstra** [comment]
It's a 640x480 VGA monitor with a VGA to HDMI converter..

What I basically need is:

```
hdmi_group=2
hdmi_mode=4
```
And looking at the code that translates to:
```
hdmi_type=monitor
hdmi_monitor_res=640x480
```
so you're right, thanks.

**Comment by thijstriemstra** [comment]
Tested, and everything looks fine. Files get cleaned up. Logs as well. Please release these goodies, cheers!

**Comment by thijstriemstra** [comment]
One thing though;

I have a master config and slave configs that extend this master file. You suggested to add this at the top of these slave configs:

```
sanitize_inputfile /bootfs/raspberrypi-ua-netinst/config/installer-config-common.txt
source /bootfs/raspberrypi-ua-netinst/config/installer-config-common.txt
```

But I'm now seeing an error about `sanitize_inputfile` not found. Should I remove that line or is there a replacement?

**Comment by FooDeas** [comment]
Replacement: inputfile_sanitize

**Comment by thijstriemstra** [comment]
Ok thanks. And about disabling the raspberries; I still see them during installation (but this could be related to `inputfile_sanitize` and my master config not being read). Will test again; seems to work now.

**Comment by FooDeas** [comment]
Boot and kernel config (like the logo) except some device settings will be set to the system only.

**Comment by FooDeas** [comment]
Done.
