### ISSUE TITLE
Does the "server" preset have components needed for GPIO program access? 

### ISSUE THREAD

**Issue by ornamentist** [FooDeas/raspberrypi-ua-netinst#84]
This is more of a question than a problem:

I'd like to use the "server" preset for a headless Raspberry Pi 3 used with a peripheral that is accessed through the GPIO pins and the R-Pi Python GPIO library.

I can post-install Python for the Python libraries but does the "server" preset install all the necessary kernel modules or other low-level software components that are needed for GPIO access?

**Comment by ornamentist** [comment]
I realize there's a setting for non-privileged access to the GPIO pins, I'm more uncertain about system-level components needed. (Ignorance showing here I know).

**Comment by FooDeas** [comment]
The server (and minimal) preset comes with all you need for GPIO access!

**Comment by ornamentist** [comment]
Excellent and thank you so much for creating and maintaining this project.
