### ISSUE TITLE
No logging of post-install

### ISSUE THREAD

**Issue by sidey79** [FooDeas/raspberrypi-ua-netinst#87]
I've a post-install.txt file

It's really simple, it just loads another script.

```
chroot rootfs /bin/bash /bootfs/raspberrypi-ua-netinst/config/chroot_config.sh
```

I'm not sure what's wrong with this, but is there anywhere a log which isn't deleted?

**Comment by FooDeas** [comment]
If the post-install prints any output, it is part of `/var/log/raspberrypi-ua-netinst.log`.
