### ISSUE TITLE
Running clean removes downloaded packages

### ISSUE THREAD

**Issue by thijstriemstra** [FooDeas/raspberrypi-ua-netinst#9]
Is it necessary to remove the downloaded packages when running `./clean.sh`? The build time would decrease a lot if it didn't re-download these packages (but I'd still like the latest version if the local ones are old). I use the normal build [instructions](https://github.com/FooDeas/raspberrypi-ua-netinst/blob/master/BUILD.md).

**Comment by FooDeas** [comment]
Normally there is no need to exec `./clean.sh`, same with `./update.sh`.
The only exception is, when you want to have updated packages from repositories included in your installation image (if there are any).
Just start the build process(es) if nothing's changed in `./update.sh` between two versions.
